import { interfacesForBuilderNode, type BuilderAddressing } from './addressing.ts';
import { builderBgpAsnForRouter, builderBgpState } from './bgp.ts';
import { builderPathCharacteristics, type BuilderLinkProfiles } from './link-characteristics.ts';
import type { BuilderGraph } from './model.ts';
import type { BuilderEvpnMacIpBinding, BuilderMplsLspConfig, BuilderProviderConfig, BuilderTunnelConfig, BuilderTunnelKind, BuilderVniConfig } from './provider-config.ts';
import { traceBuilderForwarding, type BuilderForwardingTrace, type BuilderRoutingConfig } from './routing.ts';

export interface BuilderTunnelState { tunnelId:string;kind:BuilderTunnelKind;state:'UP'|'DOWN';underlayReachable:boolean;overlayReachable:boolean;encrypted:boolean;securityState:BuilderTunnelConfig['securityState'];underlayLinkIds:string[];outerSourceAddress:string|null;outerDestinationAddress:string|null;pathMtuBytes:number|null;encapsulationOverheadBytes:number;effectiveOverlayMtuBytes:number|null;reason:string;trace:BuilderForwardingTrace; }
export interface BuilderTunnelPacketProjection { tunnelId:string;state:'ENCAPSULATED'|'DROP';inner:{source:string;destination:string;bytes:number};outer:{source:string|null;destination:string|null;protocol:string;bytes:number};effectiveOverlayMtuBytes:number|null;fragmentationRequired:boolean;reason:string;underlayLinkIds:string[]; }
export interface BuilderMplsLabelOperation { lspId:string;routerId:string;operation:'PUSH'|'SWAP'|'POP';inLabel:number|null;outLabel:number|null;outgoingLinkId:string|null;nextRouterId:string|null;fecPrefix:string; }
export interface BuilderMplsLspState { lspId:string;state:'UP'|'DOWN';reason:string;underlayTrace:BuilderForwardingTrace;routerPath:string[];linkIds:string[];operations:BuilderMplsLabelOperation[]; }
export interface BuilderVxlanPairState { aRouterId:string;bRouterId:string;reachable:boolean;linkIds:string[];reason:string; }
export interface BuilderVxlanVniState { vni:number;state:'UP'|'DEGRADED'|'DOWN';activeVtepRouterIds:string[];pairs:BuilderVxlanPairState[];reason:string; }
export interface BuilderEvpnRoute { id:string;routeType:'TYPE-2 MAC/IP';viewerVtepRouterId:string;originVtepRouterId:string;vni:number;mac:string;ip:string|null;nextHop:string;routeDistinguisher:string;routeTarget:string;learned:'LOCAL'|'BGP EVPN';underlayReachable:boolean;controlPlaneReachable:boolean;attachment:string; }
export interface BuilderEvpnImetRoute { id:string;routeType:'TYPE-3 IMET';viewerVtepRouterId:string;originVtepRouterId:string;vni:number;nextHop:string;routeTarget:string;learned:'LOCAL'|'BGP EVPN'; }
export interface BuilderVxlanForwardingResult { vni:number;sourceBindingId:string;destinationMac:string;mode:'LOCAL'|'EVPN UNICAST'|'INGRESS REPLICATION'|'DROP';delivered:boolean;remoteVtepRouterIds:string[];outerPaths:{remoteVtepRouterId:string;sourceAddress:string;destinationAddress:string;udpPort:4789;linkIds:string[];reachable:boolean}[];reason:string; }

function primaryAddress(addressing:BuilderAddressing,nodeId:string){return interfacesForBuilderNode(addressing,nodeId)[0]?.address??null;}
function linkIds(trace:BuilderForwardingTrace){return trace.hops.map((hop)=>hop.linkId).filter((id):id is string=>Boolean(id)&&id!=='discard');}
function routerPath(trace:BuilderForwardingTrace){const result=[trace.sourceNodeId];for(const hop of trace.hops)if(hop.nextNodeId&&result.at(-1)!==hop.nextNodeId)result.push(hop.nextNodeId);if(result.at(-1)!==trace.destinationNodeId)result.push(trace.destinationNodeId);return result;}
function stableHash(value:string){let hash=2166136261;for(let i=0;i<value.length;i++){hash^=value.charCodeAt(i);hash=Math.imul(hash,16777619)>>>0;}return hash>>>0;}
function labelFor(lspId:string,index:number){return 16000+((stableHash(`${lspId}:${index}`)+index*997)%800000);}
function tunnelOverhead(kind:BuilderTunnelKind){return kind==='ipip'?20:kind==='gre'?24:kind==='ipsec'?58:60;}
function encrypted(kind:BuilderTunnelKind){return kind==='ipsec'||kind==='wireguard';}
function tunnelProtocol(kind:BuilderTunnelKind){return kind==='gre'?'GRE':kind==='ipip'?'IP-IN-IP':kind==='ipsec'?'ESP-STYLE':'UDP/WIREGUARD-STYLE';}

export function builderProviderUnderlayTrace(graph:BuilderGraph,addressing:BuilderAddressing,routing:BuilderRoutingConfig,sourceRouterId:string,destinationRouterId:string,discriminator='track-g-underlay'){
  return traceBuilderForwarding(graph,addressing,routing,sourceRouterId,destinationRouterId,graph,{protocol:'udp',sourcePort:45000,destinationPort:4789,discriminator});
}

export function builderTunnelState(graph:BuilderGraph,addressing:BuilderAddressing,routing:BuilderRoutingConfig,profiles:BuilderLinkProfiles,tunnel:BuilderTunnelConfig):BuilderTunnelState{
  const trace=builderProviderUnderlayTrace(graph,addressing,routing,tunnel.sourceRouterId,tunnel.destinationRouterId,`tunnel:${tunnel.id}`),ids=linkIds(trace),characteristics=builderPathCharacteristics(profiles,ids),isEncrypted=encrypted(tunnel.kind),securityReady=!isEncrypted||tunnel.securityState==='ready';let reason='UNDERLAY REACHABLE · ENCAPSULATION READY';
  if(!tunnel.enabled)reason='TUNNEL ADMINISTRATIVELY DISABLED';else if(!trace.reachable)reason=`UNDERLAY UNREACHABLE · ${trace.failureReason??trace.explanation}`;else if(!securityReady)reason=`ENCRYPTED TUNNEL ${tunnel.securityState.toUpperCase().replaceAll('-',' ')}`;
  const up=tunnel.enabled&&trace.reachable&&securityReady,overhead=tunnelOverhead(tunnel.kind),pathMtu=characteristics.pathMtuBytes,effective=pathMtu==null?null:Math.max(68,pathMtu-overhead);
  return{tunnelId:tunnel.id,kind:tunnel.kind,state:up?'UP':'DOWN',underlayReachable:trace.reachable,overlayReachable:up,encrypted:isEncrypted,securityState:tunnel.securityState,underlayLinkIds:ids,outerSourceAddress:primaryAddress(addressing,tunnel.sourceRouterId),outerDestinationAddress:primaryAddress(addressing,tunnel.destinationRouterId),pathMtuBytes:pathMtu,encapsulationOverheadBytes:overhead,effectiveOverlayMtuBytes:effective,reason,trace};
}

export function builderTunnelPacketProjection(graph:BuilderGraph,addressing:BuilderAddressing,routing:BuilderRoutingConfig,profiles:BuilderLinkProfiles,tunnel:BuilderTunnelConfig,inner:{source:string;destination:string;bytes:number}):BuilderTunnelPacketProjection{
  const state=builderTunnelState(graph,addressing,routing,profiles,tunnel),bytes=Math.max(20,Math.round(inner.bytes)),tooLarge=state.effectiveOverlayMtuBytes!=null&&bytes>state.effectiveOverlayMtuBytes;const accepted=state.state==='UP'&&!tooLarge;
  return{tunnelId:tunnel.id,state:accepted?'ENCAPSULATED':'DROP',inner:{...inner,bytes},outer:{source:state.outerSourceAddress,destination:state.outerDestinationAddress,protocol:tunnelProtocol(tunnel.kind),bytes:bytes+state.encapsulationOverheadBytes},effectiveOverlayMtuBytes:state.effectiveOverlayMtuBytes,fragmentationRequired:tooLarge,reason:state.state!=='UP'?state.reason:tooLarge?`INNER PACKET ${bytes} B EXCEEDS EFFECTIVE TUNNEL MTU ${state.effectiveOverlayMtuBytes} B`:`INNER ${inner.source} → ${inner.destination} PRESERVED · OUTER UNDERLAY HEADER ADDED`,underlayLinkIds:state.underlayLinkIds};
}

export function builderMplsLspState(graph:BuilderGraph,addressing:BuilderAddressing,routing:BuilderRoutingConfig,lsp:BuilderMplsLspConfig):BuilderMplsLspState{
  const trace=builderProviderUnderlayTrace(graph,addressing,routing,lsp.ingressRouterId,lsp.egressRouterId,`mpls:${lsp.id}`),path=routerPath(trace),ids=linkIds(trace),enabled=new Set(routing.provider?.mpls.enabledRouterIds??[]);let reason='LSP FOLLOWS CANONICAL UNDERLAY FIB';
  if(!lsp.enabled)reason='LSP ADMINISTRATIVELY DISABLED';else if(!trace.reachable)reason=`UNDERLAY UNREACHABLE · ${trace.failureReason??trace.explanation}`;else{const missing=path.find((routerId)=>!enabled.has(routerId));if(missing)reason=`MPLS NOT ENABLED ON ${missing.toUpperCase()}`;}
  const up=lsp.enabled&&trace.reachable&&!path.some((routerId)=>!enabled.has(routerId)),operations:BuilderMplsLabelOperation[]=[];
  if(up&&path.length>=2){const labels=ids.map((_,index)=>labelFor(lsp.id,index));operations.push({lspId:lsp.id,routerId:path[0],operation:'PUSH',inLabel:null,outLabel:labels[0],outgoingLinkId:ids[0]??null,nextRouterId:path[1]??null,fecPrefix:lsp.fecPrefix});for(let i=1;i<path.length-1;i++)operations.push({lspId:lsp.id,routerId:path[i],operation:'SWAP',inLabel:labels[i-1]??null,outLabel:labels[i]??labels[i-1]??null,outgoingLinkId:ids[i]??null,nextRouterId:path[i+1]??null,fecPrefix:lsp.fecPrefix});operations.push({lspId:lsp.id,routerId:path.at(-1)!,operation:'POP',inLabel:labels.at(-1)??null,outLabel:null,outgoingLinkId:null,nextRouterId:null,fecPrefix:lsp.fecPrefix});}
  return{lspId:lsp.id,state:up?'UP':'DOWN',reason,underlayTrace:trace,routerPath:path,linkIds:ids,operations};
}

export function builderMplsForwardingTable(graph:BuilderGraph,addressing:BuilderAddressing,routing:BuilderRoutingConfig,routerId:string){return(routing.provider?.mpls.lsps??[]).flatMap((lsp)=>builderMplsLspState(graph,addressing,routing,lsp).operations).filter((row)=>row.routerId===routerId).sort((a,b)=>a.lspId.localeCompare(b.lspId));}

interface BuilderEvpnBgpPropagationState { routerId:string; learnedVia:'local'|'ibgp'|'ebgp'; learnedFromRouterId:string|null; learnedSessionId:string|null; asPath:number[]; reflectionPath:string[]; }
function bgpControlReachable(graph:BuilderGraph,addressing:BuilderAddressing,routing:BuilderRoutingConfig,originRouterId:string,viewerRouterId:string){
  if(originRouterId===viewerRouterId)return true;
  const bgp= routing.bgp, sessionState=builderBgpState(graph,addressing,bgp), established=new Set(sessionState.sessions.filter((entry)=>entry.state==='ESTABLISHED').map((entry)=>entry.id));
  const queue:BuilderEvpnBgpPropagationState[]=[{routerId:originRouterId,learnedVia:'local',learnedFromRouterId:null,learnedSessionId:null,asPath:[],reflectionPath:[]}],seen=new Set<string>();
  for(let steps=0;queue.length&&steps<256;steps+=1){const state=queue.shift()!;const fingerprint=[state.routerId,state.learnedVia,state.learnedFromRouterId??'',state.learnedSessionId??'',state.asPath.join(','),state.reflectionPath.join(',')].join('|');if(seen.has(fingerprint))continue;seen.add(fingerprint);
    for(const session of bgp.sessions){if(!established.has(session.id)||(session.aRouterId!==state.routerId&&session.bRouterId!==state.routerId))continue;const receiverId=session.aRouterId===state.routerId?session.bRouterId:session.aRouterId;if(state.learnedFromRouterId===receiverId)continue;const senderAsn=builderBgpAsnForRouter(graph,bgp,state.routerId),receiverAsn=builderBgpAsnForRouter(graph,bgp,receiverId),mode=senderAsn===receiverAsn?'ibgp':'ebgp';
      if(mode==='ibgp'&&state.learnedVia==='ibgp'){const inbound=bgp.sessions.find((entry)=>entry.id===state.learnedSessionId);const learnedFromClient=Boolean(inbound&&inbound.routeReflectorClientRouterId===state.learnedFromRouterId&&(inbound.aRouterId===state.routerId||inbound.bRouterId===state.routerId));const receiverIsClient=session.routeReflectorClientRouterId===receiverId&&(session.aRouterId===state.routerId||session.bRouterId===state.routerId);if(!learnedFromClient&&!receiverIsClient)continue;if(state.reflectionPath.includes(receiverId))continue;}
      let next:BuilderEvpnBgpPropagationState;if(mode==='ebgp'){const asPath=[senderAsn,...state.asPath];if(asPath.includes(receiverAsn))continue;next={routerId:receiverId,learnedVia:'ebgp',learnedFromRouterId:state.routerId,learnedSessionId:session.id,asPath,reflectionPath:[...state.reflectionPath]};}else next={routerId:receiverId,learnedVia:'ibgp',learnedFromRouterId:state.routerId,learnedSessionId:session.id,asPath:[...state.asPath],reflectionPath:state.learnedVia==='ibgp'?[...new Set([...state.reflectionPath,state.routerId])]:[...state.reflectionPath]};
      if(receiverId===viewerRouterId)return true;queue.push(next);
    }
  }
  return false;
}
function vtep(config:BuilderProviderConfig,routerId:string){return config.vxlan.vteps.find((entry)=>entry.routerId===routerId&&entry.enabled);}
function vni(config:BuilderProviderConfig,value:number){return config.vxlan.vnis.find((entry)=>entry.vni===value);}

export function builderVxlanVniState(graph:BuilderGraph,addressing:BuilderAddressing,routing:BuilderRoutingConfig,vniConfig:BuilderVniConfig):BuilderVxlanVniState{
  const provider=routing.provider??{tunnels:[],mpls:{enabledRouterIds:[],lsps:[]},vxlan:{vteps:[],vnis:[],bindings:[],evpnEnabled:false}},active=vniConfig.memberVtepRouterIds.filter((id)=>vtep(provider,id)),pairs:BuilderVxlanPairState[]=[];
  for(let i=0;i<active.length;i++)for(let j=i+1;j<active.length;j++){const trace=builderProviderUnderlayTrace(graph,addressing,routing,active[i],active[j],`vxlan:${vniConfig.vni}:${active[i]}:${active[j]}`);pairs.push({aRouterId:active[i],bRouterId:active[j],reachable:trace.reachable,linkIds:linkIds(trace),reason:trace.reachable?'UNDERLAY REACHABLE':trace.failureReason??trace.explanation});}
  const reachable=pairs.filter((entry)=>entry.reachable).length,total=pairs.length,state=active.length<2?'DOWN':reachable===total?'UP':reachable===0?'DOWN':'DEGRADED';return{vni:vniConfig.vni,state,activeVtepRouterIds:active,pairs,reason:state==='UP'?'ALL VTEP PAIRS HAVE CANONICAL UNDERLAY REACHABILITY':state==='DEGRADED'?'OVERLAY PARTITIONED BY UNDERLAY REACHABILITY':'VNI HAS NO COMPLETE VTEP UNDERLAY'};
}

export function builderEvpnRoutes(graph:BuilderGraph,addressing:BuilderAddressing,routing:BuilderRoutingConfig,viewerVtepRouterId:string):BuilderEvpnRoute[]{const provider=routing.provider;if(!provider?.vxlan.evpnEnabled||!vtep(provider,viewerVtepRouterId))return[];const rows:BuilderEvpnRoute[]=[];for(const binding of provider.vxlan.bindings){const network=vni(provider,binding.vni);if(!network?.memberVtepRouterIds.includes(viewerVtepRouterId))continue;const local=binding.vtepRouterId===viewerVtepRouterId,control=local||bgpControlReachable(graph,addressing,routing,binding.vtepRouterId,viewerVtepRouterId),underlay=local||builderProviderUnderlayTrace(graph,addressing,routing,viewerVtepRouterId,binding.vtepRouterId,`evpn:${binding.id}:${viewerVtepRouterId}`).reachable;if(!local&&(!control||!underlay))continue;const originVtep=vtep(provider,binding.vtepRouterId);if(!originVtep)continue;rows.push({id:`evpn2:${viewerVtepRouterId}:${binding.id}`,routeType:'TYPE-2 MAC/IP',viewerVtepRouterId,originVtepRouterId:binding.vtepRouterId,vni:binding.vni,mac:binding.mac,ip:binding.ip,nextHop:originVtep.sourceAddress,routeDistinguisher:`${builderBgpAsnForRouter(graph,routing.bgp,binding.vtepRouterId)}:${binding.vni}`,routeTarget:network.routeTarget,learned:local?'LOCAL':'BGP EVPN',underlayReachable:underlay,controlPlaneReachable:control,attachment:binding.attachment});}return rows.sort((a,b)=>a.vni-b.vni||a.mac.localeCompare(b.mac)||a.originVtepRouterId.localeCompare(b.originVtepRouterId));}

export function builderEvpnImetRoutes(graph:BuilderGraph,addressing:BuilderAddressing,routing:BuilderRoutingConfig,viewerVtepRouterId:string):BuilderEvpnImetRoute[]{const provider=routing.provider;if(!provider?.vxlan.evpnEnabled||!vtep(provider,viewerVtepRouterId))return[];const rows:BuilderEvpnImetRoute[]=[];for(const network of provider.vxlan.vnis){if(!network.memberVtepRouterIds.includes(viewerVtepRouterId))continue;for(const origin of network.memberVtepRouterIds){const originVtep=vtep(provider,origin);if(!originVtep)continue;const local=origin===viewerVtepRouterId;if(!local&&(!bgpControlReachable(graph,addressing,routing,origin,viewerVtepRouterId)||!builderProviderUnderlayTrace(graph,addressing,routing,viewerVtepRouterId,origin,`imet:${network.vni}:${origin}`).reachable))continue;rows.push({id:`evpn3:${viewerVtepRouterId}:${network.vni}:${origin}`,routeType:'TYPE-3 IMET',viewerVtepRouterId,originVtepRouterId:origin,vni:network.vni,nextHop:originVtep.sourceAddress,routeTarget:network.routeTarget,learned:local?'LOCAL':'BGP EVPN'});}}return rows.sort((a,b)=>a.vni-b.vni||a.originVtepRouterId.localeCompare(b.originVtepRouterId));}

function bindingForMac(config:BuilderProviderConfig,vniValue:number,mac:string){const normalized=mac.trim().toLowerCase().replaceAll('-',':');return config.vxlan.bindings.find((entry)=>entry.vni===vniValue&&entry.mac===normalized);}
export function builderVxlanForwarding(graph:BuilderGraph,addressing:BuilderAddressing,routing:BuilderRoutingConfig,sourceBinding:BuilderEvpnMacIpBinding,destinationMac:string):BuilderVxlanForwardingResult{
  const provider=routing.provider,network=provider? vni(provider,sourceBinding.vni):undefined,sourceVtep=provider?vtep(provider,sourceBinding.vtepRouterId):undefined;if(!provider||!network||!sourceVtep)return{vni:sourceBinding.vni,sourceBindingId:sourceBinding.id,destinationMac,mode:'DROP',delivered:false,remoteVtepRouterIds:[],outerPaths:[],reason:'SOURCE VNI/VTEP IS NOT ACTIVE'};const destination=bindingForMac(provider,sourceBinding.vni,destinationMac);if(destination?.vtepRouterId===sourceBinding.vtepRouterId)return{vni:network.vni,sourceBindingId:sourceBinding.id,destinationMac,mode:'LOCAL',delivered:true,remoteVtepRouterIds:[],outerPaths:[],reason:`DESTINATION MAC IS LOCALLY ATTACHED AT ${sourceBinding.vtepRouterId.toUpperCase()}`};
  let remotes:string[]=[];let mode:BuilderVxlanForwardingResult['mode']='INGRESS REPLICATION';if(destination&&provider.vxlan.evpnEnabled&&builderEvpnRoutes(graph,addressing,routing,sourceBinding.vtepRouterId).some((route)=>route.mac===destination.mac&&route.originVtepRouterId===destination.vtepRouterId)){remotes=[destination.vtepRouterId];mode='EVPN UNICAST';}else remotes=network.memberVtepRouterIds.filter((id)=>id!==sourceBinding.vtepRouterId&&Boolean(vtep(provider,id)));
  const outerPaths=remotes.map((remoteVtepRouterId)=>{const remote=vtep(provider,remoteVtepRouterId)!;const trace=builderProviderUnderlayTrace(graph,addressing,routing,sourceBinding.vtepRouterId,remoteVtepRouterId,`vxlan-forward:${network.vni}:${sourceBinding.id}:${destinationMac}:${remoteVtepRouterId}`);return{remoteVtepRouterId,sourceAddress:sourceVtep.sourceAddress,destinationAddress:remote.sourceAddress,udpPort:4789 as const,linkIds:linkIds(trace),reachable:trace.reachable};});const delivered=destination?outerPaths.some((entry)=>entry.remoteVtepRouterId===destination.vtepRouterId&&entry.reachable):false;return{vni:network.vni,sourceBindingId:sourceBinding.id,destinationMac,mode,delivered,remoteVtepRouterIds:remotes,outerPaths,reason:mode==='EVPN UNICAST'?(delivered?'TYPE-2 MAC/IP ROUTE SELECTED REMOTE VTEP · VXLAN USES CANONICAL UNDERLAY':'EVPN REMOTE VTEP EXISTS BUT UNDERLAY IS UNREACHABLE'):(destination?(delivered?'NO USABLE EVPN TYPE-2 ROUTE · INGRESS REPLICATION REACHES DESTINATION VTEP':'FLOOD LIST CANNOT REACH DESTINATION VTEP'):'UNKNOWN MAC · INGRESS REPLICATION ONLY; DESTINATION DELIVERY IS NOT INVENTED')};
}

export function builderProviderFacts(graph:BuilderGraph,addressing:BuilderAddressing,routing:BuilderRoutingConfig,profiles:BuilderLinkProfiles){const config=routing.provider;return{tunnels:(config?.tunnels??[]).map((entry)=>builderTunnelState(graph,addressing,routing,profiles,entry)),lsps:(config?.mpls.lsps??[]).map((entry)=>builderMplsLspState(graph,addressing,routing,entry)),vnis:(config?.vxlan.vnis??[]).map((entry)=>builderVxlanVniState(graph,addressing,routing,entry)),evpnRouteCount:(config?.vxlan.vteps??[]).reduce((sum,entry)=>sum+builderEvpnRoutes(graph,addressing,routing,entry.routerId).length,0)};}
