import { interfacesForBuilderNode, normalizeBuilderIpv4, type BuilderAddressing } from './addressing.ts';
import type { BuilderGraph } from './model.ts';

export type BuilderTunnelKind='gre'|'ipip'|'ipsec'|'wireguard';
export type BuilderTunnelSecurityState='none'|'ready'|'auth-failed'|'key-missing'|'handshake-down';
export interface BuilderTunnelConfig { id:string;kind:BuilderTunnelKind;sourceRouterId:string;destinationRouterId:string;overlayPrefix:string;localTunnelAddress:string;remoteTunnelAddress:string;enabled:boolean;securityState:BuilderTunnelSecurityState;description:string; }
export interface BuilderMplsLspConfig { id:string;ingressRouterId:string;egressRouterId:string;fecPrefix:string;enabled:boolean;description:string; }
export interface BuilderVtepConfig { routerId:string;sourceAddress:string;enabled:boolean; }
export interface BuilderVniConfig { id:string;vni:number;memberVtepRouterIds:string[];routeTarget:string;description:string; }
export interface BuilderEvpnMacIpBinding { id:string;vni:number;vtepRouterId:string;mac:string;ip:string|null;attachment:string;description:string; }
export interface BuilderProviderConfig { tunnels:BuilderTunnelConfig[];mpls:{enabledRouterIds:string[];lsps:BuilderMplsLspConfig[]};vxlan:{vteps:BuilderVtepConfig[];vnis:BuilderVniConfig[];bindings:BuilderEvpnMacIpBinding[];evpnEnabled:boolean}; }

function ipInt(value:string){return normalizeBuilderIpv4(value).split('.').reduce((n,p)=>((n<<8)|Number(p))>>>0,0)>>>0;}
function prefix(value:string){const [raw,lenText,...extra]=String(value??'').trim().split('/');const len=Number(lenText);if(!raw||extra.length||!Number.isInteger(len)||len<0||len>32)throw new Error(`Invalid IPv4 prefix ${value}.`);const address=ipInt(raw),mask=len===0?0:(0xffffffff<<(32-len))>>>0,network=(address&mask)>>>0;return{cidr:`${[24,16,8,0].map((s)=>(network>>>s)&255).join('.')}/${len}`,network,mask};}
function contains(cidr:string,address:string){const p=prefix(cidr);return ((ipInt(address)&p.mask)>>>0)===p.network;}
function text(value:unknown,max=100){return String(value??'').trim().slice(0,max);}
function id(value:unknown,label:string,seen:Set<string>){const result=text(value,160);if(!result||!/^[a-zA-Z0-9_.:-]+$/.test(result)||seen.has(result))throw new Error(`${label} needs a unique id.`);seen.add(result);return result;}
function mac(value:unknown){const raw=String(value??'').trim().toLowerCase().replaceAll('-',':');if(!/^[0-9a-f]{2}(:[0-9a-f]{2}){5}$/.test(raw))throw new Error(`Invalid MAC address ${String(value)}.`);return raw;}
function routerIds(graph:BuilderGraph){return new Set(graph.nodes.filter((node)=>node.kind==='router').map((node)=>node.id));}
function routerAddressSet(addressing:BuilderAddressing,routerId:string){return new Set(interfacesForBuilderNode(addressing,routerId).map((entry)=>entry.address));}

export function createDefaultBuilderProviderConfig():BuilderProviderConfig{return{tunnels:[],mpls:{enabledRouterIds:[],lsps:[]},vxlan:{vteps:[],vnis:[],bindings:[],evpnEnabled:false}};}
export function cloneBuilderProviderConfig(value:BuilderProviderConfig|undefined):BuilderProviderConfig{return structuredClone(value??createDefaultBuilderProviderConfig());}

export function validateBuilderProviderConfig(graph:BuilderGraph,addressing:BuilderAddressing,value:BuilderProviderConfig|undefined):BuilderProviderConfig{
  const raw=value??createDefaultBuilderProviderConfig(),routers=routerIds(graph),tunnelIds=new Set<string>();
  const tunnels=(raw.tunnels??[]).map((entry,index):BuilderTunnelConfig=>{const tunnelId=id(entry?.id,`Tunnel ${index+1}`,tunnelIds);const kind=(['gre','ipip','ipsec','wireguard'] as const).includes(entry?.kind as BuilderTunnelKind)?entry.kind:'gre';const sourceRouterId=String(entry?.sourceRouterId??''),destinationRouterId=String(entry?.destinationRouterId??'');if(!routers.has(sourceRouterId)||!routers.has(destinationRouterId)||sourceRouterId===destinationRouterId)throw new Error(`Tunnel ${tunnelId} must connect two distinct routed Builder routers.`);const overlayPrefix=prefix(String(entry?.overlayPrefix??'')).cidr,localTunnelAddress=normalizeBuilderIpv4(String(entry?.localTunnelAddress??'')),remoteTunnelAddress=normalizeBuilderIpv4(String(entry?.remoteTunnelAddress??''));if(localTunnelAddress===remoteTunnelAddress||!contains(overlayPrefix,localTunnelAddress)||!contains(overlayPrefix,remoteTunnelAddress))throw new Error(`Tunnel ${tunnelId} addresses must be distinct members of ${overlayPrefix}.`);const encrypted=kind==='ipsec'||kind==='wireguard';const securityState:BuilderTunnelSecurityState=encrypted&&(['ready','auth-failed','key-missing','handshake-down'] as const).includes(entry?.securityState as any)?entry.securityState:'none';return{id:tunnelId,kind,sourceRouterId,destinationRouterId,overlayPrefix,localTunnelAddress,remoteTunnelAddress,enabled:entry?.enabled!==false,securityState,description:text(entry?.description)};}).sort((a,b)=>a.id.localeCompare(b.id));
  const enabledRouterIds=[...new Set((raw.mpls?.enabledRouterIds??[]).map(String))].sort();if(enabledRouterIds.some((routerId)=>!routers.has(routerId)))throw new Error('MPLS may only be enabled on routed Builder routers.');const mplsSet=new Set(enabledRouterIds),lspIds=new Set<string>();
  const lsps=(raw.mpls?.lsps??[]).map((entry,index):BuilderMplsLspConfig=>{const lspId=id(entry?.id,`MPLS LSP ${index+1}`,lspIds);const ingressRouterId=String(entry?.ingressRouterId??''),egressRouterId=String(entry?.egressRouterId??'');if(ingressRouterId===egressRouterId||!mplsSet.has(ingressRouterId)||!mplsSet.has(egressRouterId))throw new Error(`MPLS LSP ${lspId} endpoints must both have MPLS enabled.`);return{id:lspId,ingressRouterId,egressRouterId,fecPrefix:prefix(String(entry?.fecPrefix??'')).cidr,enabled:entry?.enabled!==false,description:text(entry?.description)};}).sort((a,b)=>a.id.localeCompare(b.id));
  const vtepIds=new Set<string>();const vteps=(raw.vxlan?.vteps??[]).map((entry,index):BuilderVtepConfig=>{const routerId=String(entry?.routerId??'');if(!routers.has(routerId)||vtepIds.has(routerId))throw new Error(`VTEP ${index+1} must reference a unique routed Builder router.`);vtepIds.add(routerId);const sourceAddress=normalizeBuilderIpv4(String(entry?.sourceAddress??''));if(!routerAddressSet(addressing,routerId).has(sourceAddress))throw new Error(`VTEP ${routerId} source ${sourceAddress} must be an address owned by that router.`);return{routerId,sourceAddress,enabled:entry?.enabled!==false};}).sort((a,b)=>a.routerId.localeCompare(b.routerId));
  const vniIds=new Set<string>(),vniNumbers=new Set<number>();const vnis=(raw.vxlan?.vnis??[]).map((entry,index):BuilderVniConfig=>{const vniId=id(entry?.id,`VNI ${index+1}`,vniIds);const vni=Math.round(Number(entry?.vni));if(!Number.isInteger(vni)||vni<1||vni>16777215||vniNumbers.has(vni))throw new Error(`VNI ${vniId} must use a unique value from 1–16777215.`);vniNumbers.add(vni);const memberVtepRouterIds=[...new Set((entry?.memberVtepRouterIds??[]).map(String))].sort();if(memberVtepRouterIds.length<2||memberVtepRouterIds.some((routerId)=>!vtepIds.has(routerId)))throw new Error(`VNI ${vniId} requires at least two configured VTEPs.`);const routeTarget=text(entry?.routeTarget,32);if(!/^\d{1,10}:\d{1,10}$/.test(routeTarget))throw new Error(`VNI ${vniId} route target must use ASN:value notation.`);return{id:vniId,vni,memberVtepRouterIds,routeTarget,description:text(entry?.description)};}).sort((a,b)=>a.vni-b.vni);const vniSet=new Set(vnis.map((entry)=>entry.vni)),bindingIds=new Set<string>();
  const bindings=(raw.vxlan?.bindings??[]).map((entry,index):BuilderEvpnMacIpBinding=>{const bindingId=id(entry?.id,`EVPN binding ${index+1}`,bindingIds),vni=Math.round(Number(entry?.vni)),vtepRouterId=String(entry?.vtepRouterId??'');const vniConfig=vnis.find((candidate)=>candidate.vni===vni);if(!vniSet.has(vni)||!vniConfig?.memberVtepRouterIds.includes(vtepRouterId))throw new Error(`EVPN binding ${bindingId} must attach to a member VTEP of VNI ${vni}.`);const ip=entry?.ip==null||String(entry.ip).trim()===''?null:normalizeBuilderIpv4(String(entry.ip));return{id:bindingId,vni,vtepRouterId,mac:mac(entry?.mac),ip,attachment:text(entry?.attachment,64)||'LOCAL ATTACHMENT',description:text(entry?.description)};}).sort((a,b)=>a.vni-b.vni||a.mac.localeCompare(b.mac)||a.vtepRouterId.localeCompare(b.vtepRouterId));
  return{tunnels,mpls:{enabledRouterIds,lsps},vxlan:{vteps,vnis,bindings,evpnEnabled:raw.vxlan?.evpnEnabled===true}};
}

export function reconcileBuilderProviderConfig(graph:BuilderGraph,addressing:BuilderAddressing,value:BuilderProviderConfig|undefined):BuilderProviderConfig{
  const next=cloneBuilderProviderConfig(value),routers=routerIds(graph);next.tunnels=next.tunnels.filter((entry)=>routers.has(entry.sourceRouterId)&&routers.has(entry.destinationRouterId));next.mpls.enabledRouterIds=next.mpls.enabledRouterIds.filter((id)=>routers.has(id));const mpls=new Set(next.mpls.enabledRouterIds);next.mpls.lsps=next.mpls.lsps.filter((entry)=>mpls.has(entry.ingressRouterId)&&mpls.has(entry.egressRouterId));next.vxlan.vteps=next.vxlan.vteps.filter((entry)=>routers.has(entry.routerId)&&routerAddressSet(addressing,entry.routerId).has(entry.sourceAddress));const vteps=new Set(next.vxlan.vteps.map((entry)=>entry.routerId));next.vxlan.vnis=next.vxlan.vnis.map((entry)=>({...entry,memberVtepRouterIds:entry.memberVtepRouterIds.filter((id)=>vteps.has(id))})).filter((entry)=>entry.memberVtepRouterIds.length>=2);const vnis=new Map(next.vxlan.vnis.map((entry)=>[entry.vni,entry]));next.vxlan.bindings=next.vxlan.bindings.filter((entry)=>vnis.get(entry.vni)?.memberVtepRouterIds.includes(entry.vtepRouterId));return validateBuilderProviderConfig(graph,addressing,next);
}

export function upsertBuilderTunnel(config:BuilderProviderConfig,tunnel:BuilderTunnelConfig){const next=cloneBuilderProviderConfig(config);next.tunnels=[...next.tunnels.filter((entry)=>entry.id!==tunnel.id),structuredClone(tunnel)];return next;}
export function upsertBuilderMplsLsp(config:BuilderProviderConfig,lsp:BuilderMplsLspConfig){const next=cloneBuilderProviderConfig(config);next.mpls.lsps=[...next.mpls.lsps.filter((entry)=>entry.id!==lsp.id),structuredClone(lsp)];return next;}
export function upsertBuilderVtep(config:BuilderProviderConfig,vtep:BuilderVtepConfig){const next=cloneBuilderProviderConfig(config);next.vxlan.vteps=[...next.vxlan.vteps.filter((entry)=>entry.routerId!==vtep.routerId),structuredClone(vtep)];return next;}
export function upsertBuilderVni(config:BuilderProviderConfig,vni:BuilderVniConfig){const next=cloneBuilderProviderConfig(config);next.vxlan.vnis=[...next.vxlan.vnis.filter((entry)=>entry.id!==vni.id&&entry.vni!==vni.vni),structuredClone(vni)];return next;}
export function upsertBuilderEvpnBinding(config:BuilderProviderConfig,binding:BuilderEvpnMacIpBinding){const next=cloneBuilderProviderConfig(config);next.vxlan.bindings=[...next.vxlan.bindings.filter((entry)=>entry.id!==binding.id),structuredClone(binding)];return next;}
