from pathlib import Path

def replace_once(path, old, new):
    p=Path(path); s=p.read_text(encoding='utf-8'); c=s.count(old)
    if c!=1: raise SystemExit(f'{path}: expected one anchor, found {c}: {old[:120]!r}')
    p.write_text(s.replace(old,new,1),encoding='utf-8')

# BGP projection carries the exact selected best route as immutable display truth.
p=Path('src/builder/bgp.ts'); s=p.read_text(encoding='utf-8')
s=s.replace("  prefix: string | null;\n}","  prefix: string | null;\n  selectedRoute: BuilderBgpRoute | null;\n}",1)
old="const sourceAsn=sourceRouterId&&nodeIsRouter(graph,sourceRouterId)?builderBgpAsnForRouter(graph,validated,sourceRouterId):asns[0]??null;const destinationAsn=destinationRouterId&&nodeIsRouter(graph,destinationRouterId)?builderBgpAsnForRouter(graph,validated,destinationRouterId):asns.at(-1)??null;const winner=state&&sourceRouterId?state.bestRoutes.find((route)=>route.routerId===sourceRouterId&&(!prefix||route.prefix===parsePrefix(prefix).cidr)):null;const selectedPathAsns=winner&&sourceAsn?[sourceAsn,...winner.asPath].filter((asn,index,all)=>index===0||asn!==all[index-1]):[];return{graph:{nodes,relationships:[...relMap.values()].sort((a,b)=>a.id.localeCompare(b.id))},sourceAsn,destinationAsn,selectedPathAsns,prefix:winner?.prefix??(prefix?parsePrefix(prefix).cidr:null)};"
new="const sourceAsn=sourceRouterId&&nodeIsRouter(graph,sourceRouterId)?builderBgpAsnForRouter(graph,validated,sourceRouterId):asns[0]??null;const winner=state&&sourceRouterId?state.bestRoutes.find((route)=>route.routerId===sourceRouterId&&(!prefix||route.prefix===parsePrefix(prefix).cidr)):null;const destinationAsn=destinationRouterId&&nodeIsRouter(graph,destinationRouterId)?builderBgpAsnForRouter(graph,validated,destinationRouterId):(winner?.originAsn??asns.at(-1)??null);const selectedPathAsns=winner&&sourceAsn?[sourceAsn,...winner.asPath].filter((asn,index,all)=>index===0||asn!==all[index-1]):[];const selectedRoute=winner?{...winner,asPath:[...winner.asPath],communities:[...winner.communities]}:null;return{graph:{nodes,relationships:[...relMap.values()].sort((a,b)=>a.id.localeCompare(b.id))},sourceAsn,destinationAsn,selectedPathAsns,prefix:winner?.prefix??(prefix?parsePrefix(prefix).cidr:null),selectedRoute};"
if s.count(old)!=1: raise SystemExit(f'bgp projection body anchor found {s.count(old)}')
p.write_text(s.replace(old,new,1),encoding='utf-8')

# Builder BGP panel gains a projection action; it only opens when a concrete selected best route exists.
p=Path('src/BuilderBgpPanel.tsx'); s=p.read_text(encoding='utf-8')
s=s.replace("  type BuilderBgpPolicyDirection,\n", "  type BuilderBgpPolicyDirection,\n  type BuilderBgpAsProjection,\n",1)
old="export function BuilderBgpPanel({graph,addressing,routing,selectedNodeId,selectedLinkId,destinationPrefix,onChange,onMessage}:{graph:BuilderGraph;addressing:BuilderAddressing;routing:BuilderRoutingConfig;selectedNodeId:string;selectedLinkId:string;destinationPrefix:string;onChange:(next:BuilderRoutingConfig)=>void;onMessage:(message:string)=>void;}){"
new="export function BuilderBgpPanel({graph,addressing,routing,selectedNodeId,selectedLinkId,destinationPrefix,onChange,onMessage,onOpenAsProjection}:{graph:BuilderGraph;addressing:BuilderAddressing;routing:BuilderRoutingConfig;selectedNodeId:string;selectedLinkId:string;destinationPrefix:string;onChange:(next:BuilderRoutingConfig)=>void;onMessage:(message:string)=>void;onOpenAsProjection?:(projection:BuilderBgpAsProjection)=>void;}){"
if s.count(old)!=1: raise SystemExit('BuilderBgpPanel signature anchor missing')
s=s.replace(old,new,1)
old="<div className=\"builder-ospf-facts\"><div><span>ANOMALIES</span><strong>{state.multiOriginPrefixes.length} MULTI-ORIGIN · {state.leakedRouteIds.length} LEAKED</strong></div><div><span>AS PROJECTION</span><strong>{projection.graph.nodes.length} AS · {projection.graph.relationships.length} REL</strong></div></div>"
new="<div className=\"builder-ospf-facts\"><div><span>ANOMALIES</span><strong>{state.multiOriginPrefixes.length} MULTI-ORIGIN · {state.leakedRouteIds.length} LEAKED</strong></div><div><span>AS PROJECTION</span><strong>{projection.graph.nodes.length} AS · {projection.graph.relationships.length} REL</strong></div></div><div className=\"button-row\"><button type=\"button\" disabled={!onOpenAsProjection||!projection.selectedRoute||projection.selectedPathAsns.length===0} onClick={()=>projection.selectedRoute&&onOpenAsProjection?.(projection)}>OPEN AS PROJECTION ↗</button></div>{projection.selectedRoute&&<small className=\"builder-routing-note\">PROJECTION READY · AS{projection.sourceAsn} → AS{projection.destinationAsn} · {projection.prefix} · exact Builder BEST path {projection.selectedPathAsns.map((asn)=>`AS${asn}`).join(' → ')}.</small>}"
if s.count(old)!=1: raise SystemExit('BuilderBgpPanel projection facts anchor missing')
p.write_text(s.replace(old,new,1),encoding='utf-8')

# Builder can receive every persisted scenario field on return and snapshots its exact current config before opening AS scale.
p=Path('src/NetworkBuilder.tsx'); s=p.read_text(encoding='utf-8')
s=s.replace("import { BuilderBgpPanel } from './BuilderBgpPanel.tsx';\n", "import { BuilderBgpPanel } from './BuilderBgpPanel.tsx';\nimport type { BuilderBgpAsProjection } from './builder/bgp.ts';\nimport { cloneBuilderDhcpConfig, createDefaultBuilderDhcpConfig, type BuilderDhcpConfig } from './builder/dhcp.ts';\n",1)
old="export function NetworkBuilder({ onExit, onOpenFailureStory, onOpenProbePacket, initialGraph = defaultBuilderGraph, initialLayout = defaultBuilderLayout, initialAddressing, initialRouting, initialEthernet, initialNat, initialIpv6, initialSourceId = 'client', initialDestinationId = 'app', stressLabel }: { onExit: () => void; onOpenFailureStory: () => void; onOpenProbePacket?: (seed: BuilderProbePacketSeed) => void; initialGraph?: BuilderGraph; initialLayout?: BuilderLayout; initialAddressing?: BuilderAddressing; initialRouting?: BuilderRoutingConfig; initialEthernet?: BuilderEthernetConfig; initialNat?: BuilderNatConfig; initialIpv6?: BuilderIpv6Config; initialSourceId?: string; initialDestinationId?: string; stressLabel?: string }) {"
new="export function NetworkBuilder({ onExit, onOpenFailureStory, onOpenProbePacket, onOpenBgpProjection, initialGraph = defaultBuilderGraph, initialLayout = defaultBuilderLayout, initialAddressing, initialRouting, initialEthernet, initialLinkProfiles, initialAcl, initialNat, initialDhcp, initialIpv6, initialSourceId = 'client', initialDestinationId = 'app', initialScenarioName = 'My topology', stressLabel }: { onExit: () => void; onOpenFailureStory: () => void; onOpenProbePacket?: (seed: BuilderProbePacketSeed) => void; onOpenBgpProjection?: (payload: { projection: BuilderBgpAsProjection; scenario: BuilderScenarioV8 }) => void; initialGraph?: BuilderGraph; initialLayout?: BuilderLayout; initialAddressing?: BuilderAddressing; initialRouting?: BuilderRoutingConfig; initialEthernet?: BuilderEthernetConfig; initialLinkProfiles?: BuilderLinkProfiles; initialAcl?: BuilderAclConfig; initialNat?: BuilderNatConfig; initialDhcp?: BuilderDhcpConfig; initialIpv6?: BuilderIpv6Config; initialSourceId?: string; initialDestinationId?: string; initialScenarioName?: string; stressLabel?: string }) {"
if s.count(old)!=1: raise SystemExit('NetworkBuilder signature anchor missing')
s=s.replace(old,new,1)
s=s.replace("const [linkProfiles, setLinkProfiles] = useState<BuilderLinkProfiles>(() => createDefaultBuilderLinkProfiles(initialGraph));","const [linkProfiles, setLinkProfiles] = useState<BuilderLinkProfiles>(() => cloneBuilderLinkProfiles(initialLinkProfiles ?? createDefaultBuilderLinkProfiles(initialGraph)));",1)
s=s.replace("const [acl, setAcl] = useState<BuilderAclConfig>(() => createDefaultBuilderAclConfig());","const [acl, setAcl] = useState<BuilderAclConfig>(() => cloneBuilderAclConfig(initialAcl ?? createDefaultBuilderAclConfig()));",1)
s=s.replace("const [nat, setNat] = useState<BuilderNatConfig>(() => cloneBuilderNatConfig(initialNat ?? (stressLabel ? createEmptyBuilderNatConfig() : createDefaultBuilderNatConfig(initialGraph))));","const [nat, setNat] = useState<BuilderNatConfig>(() => cloneBuilderNatConfig(initialNat ?? (stressLabel ? createEmptyBuilderNatConfig() : createDefaultBuilderNatConfig(initialGraph))));\n  const [dhcp, setDhcp] = useState<BuilderDhcpConfig>(() => cloneBuilderDhcpConfig(initialDhcp ?? createDefaultBuilderDhcpConfig(initialEthernet ?? (stressLabel ? createEmptyBuilderEthernetConfig() : createDefaultBuilderEthernetConfig()))));",1)
s=s.replace("const [scenarioName, setScenarioName] = useState('My topology');","const [scenarioName, setScenarioName] = useState(initialScenarioName);",1)
# Reset persisted config to exact initial values.
s=s.replace("setEthernet(cloneBuilderEthernetConfig(initialEthernet ?? createDefaultBuilderEthernetConfig())); setEthernetFlow(null); setLinkProfiles(createDefaultBuilderLinkProfiles(initialGraph)); setAcl(createDefaultBuilderAclConfig()); setNat(cloneBuilderNatConfig(initialNat ?? createDefaultBuilderNatConfig(initialGraph)));", "setEthernet(cloneBuilderEthernetConfig(initialEthernet ?? createDefaultBuilderEthernetConfig())); setEthernetFlow(null); setLinkProfiles(cloneBuilderLinkProfiles(initialLinkProfiles ?? createDefaultBuilderLinkProfiles(initialGraph))); setAcl(cloneBuilderAclConfig(initialAcl ?? createDefaultBuilderAclConfig())); setNat(cloneBuilderNatConfig(initialNat ?? createDefaultBuilderNatConfig(initialGraph))); setDhcp(cloneBuilderDhcpConfig(initialDhcp ?? createDefaultBuilderDhcpConfig(initialEthernet ?? createDefaultBuilderEthernetConfig())));",1)
s=s.replace("setSourceId(initialSourceId); setDestinationId(initialDestinationId); setSelectedNodeId(initialSourceId);", "setSourceId(initialSourceId); setDestinationId(initialDestinationId); setSelectedNodeId(initialSourceId); setScenarioName(initialScenarioName);",1)
# Save/export must preserve DHCP config instead of recreating a default on every snapshot.
s=s.replace("createBuilderScenario(scenarioName.trim() || 'Untitled topology', graph, sourceId, destinationId, layout, addressing, routing, existing, ethernet, linkProfiles, acl, nat, undefined, ipv6)","createBuilderScenario(scenarioName.trim() || 'Untitled topology', graph, sourceId, destinationId, layout, addressing, routing, existing, ethernet, linkProfiles, acl, nat, dhcp, ipv6)",1)
s=s.replace("setNat(cloneBuilderNatConfig(scenario.nat)); setNatSessions", "setNat(cloneBuilderNatConfig(scenario.nat)); setDhcp(cloneBuilderDhcpConfig(scenario.dhcp)); setNatSessions",1)
s=s.replace("createBuilderScenario(scenarioName.trim() || 'Exported topology', graph, sourceId, destinationId, layout, addressing, routing, undefined, ethernet, linkProfiles, acl, nat, undefined, ipv6)","createBuilderScenario(scenarioName.trim() || 'Exported topology', graph, sourceId, destinationId, layout, addressing, routing, undefined, ethernet, linkProfiles, acl, nat, dhcp, ipv6)",1)
# Wrap BGP projection in a full Builder snapshot.
anchor="  const onNodeDragEnd = (nodeId: string, offsetX: number, offsetY: number) => {"
insert="""  const openBgpProjection = (projection: BuilderBgpAsProjection) => {\n    if (!onOpenBgpProjection || !projection.selectedRoute) { setMessage('BGP AS PROJECTION · select a router/prefix with a concrete BEST route first.'); return; }\n    try {\n      const scenario = createBuilderScenario(scenarioName.trim() || 'BGP projection', graph, sourceId, destinationId, layout, addressing, routing, undefined, ethernet, linkProfiles, acl, nat, dhcp, ipv6);\n      onOpenBgpProjection({ projection, scenario });\n    } catch (error) { setMessage(`BGP PROJECTION REJECTED · ${error instanceof Error ? error.message : 'Unable to snapshot Builder truth.'}`); }\n  };\n\n  const onNodeDragEnd = (nodeId: string, offsetX: number, offsetY: number) => {"""
if s.count(anchor)!=1: raise SystemExit('NetworkBuilder onNodeDragEnd anchor missing')
s=s.replace(anchor,insert,1)
old="<BuilderBgpPanel graph={graph} addressing={addressing} routing={routing} selectedNodeId={selectedNodeId} selectedLinkId={selectedLinkId} destinationPrefix={destinationPrefix} onChange={setRouting} onMessage={setMessage}/>"
new="<BuilderBgpPanel graph={graph} addressing={addressing} routing={routing} selectedNodeId={selectedNodeId} selectedLinkId={selectedLinkId} destinationPrefix={destinationPrefix} onChange={setRouting} onMessage={setMessage} onOpenAsProjection={onOpenBgpProjection}/>"
if s.count(old)!=1: raise SystemExit('NetworkBuilder BGP panel anchor missing')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')

# Internet theater accepts a locked Builder BGP projection and never recomputes its winner.
p=Path('src/InternetScaleTheater.tsx'); s=p.read_text(encoding='utf-8')
s=s.replace("import './InternetScaleTheater.css';\n", "import type { BuilderBgpAsProjection } from './builder/bgp.ts';\nimport './InternetScaleTheater.css';\n",1)
old="export function InternetScaleTheater({ onExit, onOpenObserved, graph = simulatedAsGraph, initialSource = DEFAULT_AS_SOURCE, initialDestination = DEFAULT_AS_DESTINATION, stressLabel }: { onExit: () => void; onOpenObserved: () => void; graph?: SimulatedAsGraph; initialSource?: number; initialDestination?: number; stressLabel?: string }) {\n  const canvasRef = useRef<HTMLCanvasElement>(null);"
new="export function InternetScaleTheater({ onExit, onOpenObserved, graph: inputGraph = simulatedAsGraph, initialSource = DEFAULT_AS_SOURCE, initialDestination = DEFAULT_AS_DESTINATION, builderProjection, onReturnToBuilder, stressLabel }: { onExit: () => void; onOpenObserved: () => void; graph?: SimulatedAsGraph; initialSource?: number; initialDestination?: number; builderProjection?: BuilderBgpAsProjection | null; onReturnToBuilder?: () => void; stressLabel?: string }) {\n  const graph = builderProjection?.graph ?? inputGraph;\n  const projectionLocked = Boolean(builderProjection);\n  const canvasRef = useRef<HTMLCanvasElement>(null);"
if s.count(old)!=1: raise SystemExit('Internet theater signature anchor missing')
s=s.replace(old,new,1)
s=s.replace("const [source, setSource] = useState(initialSource);\n  const [destination, setDestination] = useState(initialDestination);", "const [source, setSource] = useState(builderProjection?.sourceAsn ?? initialSource);\n  const [destination, setDestination] = useState(builderProjection?.destinationAsn ?? initialDestination);",1)
old="  const candidates = useMemo(() => enumeratePolicyPaths(graph, source, destination, failed), [graph, source, destination, failed]);\n  const winner = candidates[0];"
new="""  const projectedWinner = useMemo(() => {\n    if (!builderProjection || builderProjection.selectedPathAsns.length === 0) return null;\n    const relationshipIds: string[] = [];\n    for (let index = 0; index < builderProjection.selectedPathAsns.length - 1; index += 1) {\n      const a = builderProjection.selectedPathAsns[index], b = builderProjection.selectedPathAsns[index + 1];\n      const relationship = graph.relationships.find((entry) => relationshipEndpoints(entry).includes(a) && relationshipEndpoints(entry).includes(b));\n      if (relationship) relationshipIds.push(relationship.id);\n    }\n    return { asns: [...builderProjection.selectedPathAsns], relationshipIds, scoreLabel: `BUILDER BGP BEST · ${builderProjection.prefix ?? 'NLRI'}` };\n  }, [builderProjection, graph]);\n  const candidates = useMemo(() => builderProjection ? (projectedWinner ? [projectedWinner] : []) : enumeratePolicyPaths(graph, source, destination, failed), [builderProjection, projectedWinner, graph, source, destination, failed]);\n  const winner = candidates[0];"
if s.count(old)!=1: raise SystemExit('Internet candidates anchor missing')
s=s.replace(old,new,1)
# Keep projection endpoints and failures locked if the prop changes.
anchor="  const selectedRelationship = graph.relationships.find((item) => item.id === selectedRelationshipId) ?? graph.relationships[0];\n  const activeRelationships = new Set(winner?.relationshipIds ?? []);\n"
insert="""  const selectedRelationship = graph.relationships.find((item) => item.id === selectedRelationshipId) ?? graph.relationships[0];\n  const activeRelationships = new Set(winner?.relationshipIds ?? []);\n\n  useEffect(() => {\n    if (!builderProjection) return;\n    if (builderProjection.sourceAsn != null) setSource(builderProjection.sourceAsn);\n    if (builderProjection.destinationAsn != null) setDestination(builderProjection.destinationAsn);\n    setFailed(new Set()); setPickMode(null);\n    setSelectedRelationshipId(builderProjection.graph.relationships[0]?.id ?? '');\n  }, [builderProjection]);\n"""
if s.count(anchor)!=1: raise SystemExit('Internet selected relationship anchor missing')
s=s.replace(anchor,insert,1)
s=s.replace("    if (pickMode) {", "    if (pickMode && !projectionLocked) {",1)
s=s.replace("  const toggleRelationship = (relationship: AsRelationship) => {\n    setFailed", "  const toggleRelationship = (relationship: AsRelationship) => {\n    if (projectionLocked) return;\n    setFailed",1)
# Header and main meta/winner exact projection copy.
old='<header className="internet-heading"><div><p className="eyebrow">Lab 05A · Internet scale</p><h1>POLICY MAKES<br/><span>THE PATH.</span></h1></div><div className="internet-heading-actions"><span>SIMULATED · DOCUMENTATION ASNs ONLY</span><button className="lab-mode" type="button" onClick={onOpenObserved}>OBSERVED / INFERRED ↗</button><button className="lab-mode" type="button" onClick={onExit}>EXIT LAB</button></div></header>'
new='<header className="internet-heading"><div><p className="eyebrow">{projectionLocked?\'Lab 11O → 05A · BGP projection\':\'Lab 05A · Internet scale\'}</p><h1>{projectionLocked?<>BUILDER BGP.<br/><span>AS SCALE.</span></>:<>POLICY MAKES<br/><span>THE PATH.</span></>}</h1></div><div className="internet-heading-actions"><span>{projectionLocked?\'BUILDER BGP PROJECTION · DOCUMENTATION ASNs\':\'SIMULATED · DOCUMENTATION ASNs ONLY\'}</span>{projectionLocked&&onReturnToBuilder&&<button className="lab-mode" type="button" onClick={onReturnToBuilder}>RETURN TO BUILDER ↗</button>}{!projectionLocked&&<button className="lab-mode" type="button" onClick={onOpenObserved}>OBSERVED / INFERRED ↗</button>}<button className="lab-mode" type="button" onClick={onExit}>EXIT LAB</button></div></header>'
if s.count(old)!=1: raise SystemExit('Internet header anchor missing')
s=s.replace(old,new,1)
old="<section className=\"internet-stage\"><div className=\"internet-stage-meta\"><div><span>SOURCE</span><strong>{asLabel(source)}</strong></div><div><span>DESTINATION</span><strong>{asLabel(destination)}</strong></div><div><span>CANDIDATES</span><strong>{candidates.length}</strong></div><div><span>SELECTED</span><strong>{winner ? `${winner.relationshipIds.length} AS HOPS` : 'UNREACHABLE'}</strong></div></div>"
new="<section className=\"internet-stage\"><div className=\"internet-stage-meta\"><div><span>SOURCE</span><strong>{asLabel(source)}</strong></div><div><span>DESTINATION</span><strong>{asLabel(destination)}</strong></div><div><span>{projectionLocked?'TRUTH':'CANDIDATES'}</span><strong>{projectionLocked?'BUILDER BEST':candidates.length}</strong></div><div><span>SELECTED</span><strong>{winner ? `${winner.relationshipIds.length} AS HOPS` : 'UNREACHABLE'}</strong></div></div>"
if s.count(old)!=1: raise SystemExit('Internet stage meta anchor missing')
s=s.replace(old,new,1)
old="{winner?<div className=\"internet-winner\"><span>SIMULATED WINNER</span><strong>{winner.asns.map(asLabel).join(' → ')}</strong><p>{winner.scoreLabel} · stable ASN-path tie break. Curated valley-free teaching policy, not universal BGP best-path behavior.</p></div>:"
new="{winner?<div className=\"internet-winner\"><span>{projectionLocked?'BUILDER BGP BEST PATH':'SIMULATED WINNER'}</span><strong>{winner.asns.map(asLabel).join(' → ')}</strong><p>{projectionLocked?'Exact Builder BGP decision projected at AS scale. Lab 05 is not recomputing a different winner.':`${winner.scoreLabel} · stable ASN-path tie break. Curated valley-free teaching policy, not universal BGP best-path behavior.`}</p></div>:"
if s.count(old)!=1: raise SystemExit('Internet winner anchor missing')
s=s.replace(old,new,1)
# Replace endpoint controls and failure button behavior with locked projection facts where appropriate.
old='<section><div className="internet-panel-title"><span>ENDPOINTS</span><strong>PICK FROM CANVAS</strong></div><label>SOURCE<select value={source} onChange={(e)=>setSource(Number(e.currentTarget.value))}>{graph.nodes.map((node)=><option key={node.asn} value={node.asn}>{node.label} · {node.role}</option>)}</select></label><label>DESTINATION<select value={destination} onChange={(e)=>setDestination(Number(e.currentTarget.value))}>{graph.nodes.map((node)=><option key={node.asn} value={node.asn}>{node.label} · {node.role}</option>)}</select></label><div className="internet-buttons"><button type="button" onClick={()=>setPickMode(\'source\')}>PICK SOURCE</button><button type="button" onClick={()=>setPickMode(\'destination\')}>PICK DEST</button></div></section>'
new='<section><div className="internet-panel-title"><span>{projectionLocked?\'BUILDER TRUTH\':\'ENDPOINTS\'}</span><strong>{projectionLocked?\'LOCKED PROJECTION\':\'PICK FROM CANVAS\'}</strong></div>{projectionLocked?<><p className="relationship-copy">PREFIX · {builderProjection?.prefix??\'—\'}</p><p className="relationship-copy">SOURCE {asLabel(source)} · ORIGIN {asLabel(destination)}</p>{builderProjection?.selectedRoute&&<p className="relationship-copy">LOCAL_PREF {builderProjection.selectedRoute.localPref} · AS_PATH {builderProjection.selectedRoute.asPath.join(\' → \')||\'LOCAL\'} · MED {builderProjection.selectedRoute.med} · NEXT_HOP {builderProjection.selectedRoute.nextHopAddress} · COMM {builderProjection.selectedRoute.communities.join(\' \')||\'NONE\'}{builderProjection.selectedRoute.policyAnomaly?\' · POLICY ANOMALY\':\'\'}</p>}</>:<><label>SOURCE<select value={source} onChange={(e)=>setSource(Number(e.currentTarget.value))}>{graph.nodes.map((node)=><option key={node.asn} value={node.asn}>{node.label} · {node.role}</option>)}</select></label><label>DESTINATION<select value={destination} onChange={(e)=>setDestination(Number(e.currentTarget.value))}>{graph.nodes.map((node)=><option key={node.asn} value={node.asn}>{node.label} · {node.role}</option>)}</select></label><div className="internet-buttons"><button type="button" onClick={()=>setPickMode(\'source\')}>PICK SOURCE</button><button type="button" onClick={()=>setPickMode(\'destination\')}>PICK DEST</button></div></>}</section>'
if s.count(old)!=1: raise SystemExit('Internet endpoints panel anchor missing')
s=s.replace(old,new,1)
old="<button className={failed.has(selectedRelationship.id)?'restore':''} type=\"button\" onClick={()=>toggleRelationship(selectedRelationship)}>{failed.has(selectedRelationship.id)?'RESTORE RELATIONSHIP':'FAIL RELATIONSHIP'}</button>"
new="{projectionLocked?<small>READ ONLY · return to Builder to mutate sessions, relationships, or policy.</small>:<button className={failed.has(selectedRelationship.id)?'restore':''} type=\"button\" onClick={()=>toggleRelationship(selectedRelationship)}>{failed.has(selectedRelationship.id)?'RESTORE RELATIONSHIP':'FAIL RELATIONSHIP'}</button>}"
if s.count(old)!=1: raise SystemExit('Internet fail relationship anchor missing')
s=s.replace(old,new,1)
# Candidate heading and reset behavior.
s=s.replace('<div className="internet-panel-title"><span>CANDIDATE PATHS</span><strong>POLICY ORDER</strong></div>','<div className="internet-panel-title"><span>{projectionLocked?\'PROJECTED PATH\':\'CANDIDATE PATHS\'}</span><strong>{projectionLocked?\'NO RECOMPUTE\':\'POLICY ORDER\'}</strong></div>',1)
old="<button type=\"button\" onClick={()=>{setFailed(new Set());setSource(DEFAULT_AS_SOURCE);setDestination(DEFAULT_AS_DESTINATION);setZoom(1);}}>RESET</button>"
new="<button type=\"button\" onClick={()=>{setFailed(new Set());if(!projectionLocked){setSource(DEFAULT_AS_SOURCE);setDestination(DEFAULT_AS_DESTINATION);}setZoom(1);}}>RESET VIEW</button>"
if s.count(old)!=1: raise SystemExit('Internet reset anchor missing')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')

# App owns a full snapshot + projection pair and switches between labs without mutating either.
p=Path('src/App.tsx'); s=p.read_text(encoding='utf-8')
s=s.replace("import type { BuilderProbePacketSeed } from './builder/probes.ts';\n", "import type { BuilderProbePacketSeed } from './builder/probes.ts';\nimport type { BuilderScenarioV8 } from './builder/scenario.ts';\nimport type { BuilderBgpAsProjection } from './builder/bgp.ts';\n",1)
s=s.replace("const [builderPacketSeed, setBuilderPacketSeed] = useState<BuilderProbePacketSeed | null>(null);", "const [builderPacketSeed, setBuilderPacketSeed] = useState<BuilderProbePacketSeed | null>(null);\n  const [builderBgpProjection, setBuilderBgpProjection] = useState<{ projection: BuilderBgpAsProjection; scenario: BuilderScenarioV8 } | null>(null);",1)
# Normal lab opening clears stale projection; projection return uses a dedicated callback.
s=s.replace("const openBuilderLab = () => { pushBrowserRoute('builder'); setPlaying(false); setLayer('routing'); setActiveLab('builder'); };", "const openBuilderLab = () => { setBuilderBgpProjection(null); pushBrowserRoute('builder'); setPlaying(false); setLayer('routing'); setActiveLab('builder'); };\n  const openBuilderBgpProjection = (payload: { projection: BuilderBgpAsProjection; scenario: BuilderScenarioV8 }) => { setBuilderBgpProjection(payload); pushBrowserRoute('internet'); setPlaying(false); setLayer('internet'); setActiveLab('internet'); };\n  const returnToProjectedBuilder = () => { if (!builderBgpProjection) { openBuilderLab(); return; } pushBrowserRoute('builder'); setPlaying(false); setLayer('routing'); setActiveLab('builder'); };",1)
s=s.replace("const openInternetLab = () => { pushBrowserRoute('internet'); setPlaying(false); setLayer('internet'); setActiveLab('internet'); };", "const openInternetLab = () => { setBuilderBgpProjection(null); pushBrowserRoute('internet'); setPlaying(false); setLayer('internet'); setActiveLab('internet'); };",1)
s=s.replace("const exitLabs = () => { pushBrowserRoute(null); setPlaying(false); setJourneyReturnPending(false); setExploreOpen(false); setActiveLab(null); };", "const exitLabs = () => { pushBrowserRoute(null); setPlaying(false); setJourneyReturnPending(false); setExploreOpen(false); setBuilderBgpProjection(null); setActiveLab(null); };",1)
s=s.replace("? 'SIMULATED AS THEATER ACTIVE'", "? (builderBgpProjection ? 'BUILDER BGP AS PROJECTION' : 'SIMULATED AS THEATER ACTIVE')",1)
old='<NetworkBuilder key="lab04" onExit={exitActiveLab} onOpenFailureStory={() => openFailureLab(0, true)} onOpenProbePacket={openPacketLab} />'
new='<NetworkBuilder key={`lab04-${builderBgpProjection?.scenario.updatedAt??\'default\'}`} onExit={exitActiveLab} onOpenFailureStory={() => openFailureLab(0, true)} onOpenProbePacket={openPacketLab} onOpenBgpProjection={openBuilderBgpProjection} initialGraph={builderBgpProjection?.scenario.graph} initialLayout={builderBgpProjection?.scenario.layout} initialAddressing={builderBgpProjection?.scenario.addressing} initialRouting={builderBgpProjection?.scenario.routing} initialEthernet={builderBgpProjection?.scenario.ethernet} initialLinkProfiles={builderBgpProjection?.scenario.linkProfiles} initialAcl={builderBgpProjection?.scenario.acl} initialNat={builderBgpProjection?.scenario.nat} initialDhcp={builderBgpProjection?.scenario.dhcp} initialIpv6={builderBgpProjection?.scenario.ipv6} initialSourceId={builderBgpProjection?.scenario.sourceId} initialDestinationId={builderBgpProjection?.scenario.destinationId} initialScenarioName={builderBgpProjection?.scenario.name}/>'
if s.count(old)!=1: raise SystemExit('App NetworkBuilder render anchor missing')
s=s.replace(old,new,1)
old='<InternetScaleTheater key="lab05-simulated" onExit={exitActiveLab} onOpenObserved={openObservedInternet} />'
new='<InternetScaleTheater key={`lab05-simulated-${builderBgpProjection?\'builder-bgp\':\'default\'}`} onExit={exitActiveLab} onOpenObserved={openObservedInternet} builderProjection={builderBgpProjection?.projection} onReturnToBuilder={builderBgpProjection?returnToProjectedBuilder:undefined}/>'
if s.count(old)!=1: raise SystemExit('App InternetScale render anchor missing')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')

# Permanent round-trip/projection model contract.
Path('scripts/builder-bgp-projection-contract-check.mjs').write_text(r'''import assert from 'node:assert/strict';
import { createDefaultBuilderAddressing } from '../src/builder/addressing.ts';
import { cloneBuilderGraph, defaultBuilderGraph, defaultBuilderLayout } from '../src/builder/model.ts';
import { createDefaultBuilderRoutingConfig } from '../src/builder/routing.ts';
import { createBuilderScenario, deserializeBuilderScenario, serializeBuilderScenario } from '../src/builder/scenario.ts';
import { createDefaultBuilderEthernetConfig } from '../src/builder/ethernet.ts';
import { createDefaultBuilderLinkProfiles } from '../src/builder/link-characteristics.ts';
import { createDefaultBuilderAclConfig } from '../src/builder/acl.ts';
import { createDefaultBuilderNatConfig } from '../src/builder/nat.ts';
import { createDefaultBuilderDhcpConfig } from '../src/builder/dhcp.ts';
import { createDefaultBuilderIpv6Config } from '../src/builder/ipv6.ts';
import { builderBgpState, projectBuilderBgpToAsGraph, setBuilderBgpRouterAsn, updateBuilderBgpSession, upsertBuilderBgpOrigin, upsertBuilderBgpSession } from '../src/builder/bgp.ts';

const graph=cloneBuilderGraph(defaultBuilderGraph),addressing=createDefaultBuilderAddressing(graph);let routing=createDefaultBuilderRoutingConfig();
let bgp=routing.bgp;bgp=setBuilderBgpRouterAsn(graph,bgp,'edge',64496);bgp=setBuilderBgpRouterAsn(graph,bgp,'r1',64500);bgp=setBuilderBgpRouterAsn(graph,bgp,'r2',64500);bgp=setBuilderBgpRouterAsn(graph,bgp,'core',65538);
bgp=upsertBuilderBgpSession(graph,bgp,'edge-r1','customer-provider');let s=bgp.sessions.find((entry)=>entry.linkId==='edge-r1');bgp=updateBuilderBgpSession(graph,bgp,s.id,{customerRouterId:'edge'});
bgp=upsertBuilderBgpSession(graph,bgp,'r1-r2','peer');s=bgp.sessions.find((entry)=>entry.linkId==='r1-r2');bgp=updateBuilderBgpSession(graph,bgp,s.id,{nextHopSelf:true});
bgp=upsertBuilderBgpSession(graph,bgp,'r2-core','customer-provider');s=bgp.sessions.find((entry)=>entry.linkId==='r2-core');bgp=updateBuilderBgpSession(graph,bgp,s.id,{customerRouterId:'r2'});
const prefix=addressing.segments['core-app'].cidr;bgp=upsertBuilderBgpOrigin(graph,bgp,{routerId:'core',prefix,med:7,communities:['65538:777'],description:'projection target'});routing={...routing,bgp};
const state=builderBgpState(graph,addressing,bgp),best=state.bestRoutes.find((route)=>route.routerId==='edge'&&route.prefix===prefix);assert.ok(best);const projection=projectBuilderBgpToAsGraph(graph,bgp,state,'edge',undefined,prefix);
assert.deepEqual(projection.selectedPathAsns,[64496,...best.asPath]);assert.equal(projection.sourceAsn,64496);assert.equal(projection.destinationAsn,best.originAsn);assert.equal(projection.selectedRoute?.id,best.id);assert.deepEqual(projection.selectedRoute?.communities,best.communities);assert.equal(projection.selectedRoute?.localPref,best.localPref);assert.ok(projection.graph.nodes.every((node)=>[64496,64500,65538].includes(node.asn)));assert.ok(projection.graph.relationships.length>=2);
const ethernet=createDefaultBuilderEthernetConfig(),dhcp=createDefaultBuilderDhcpConfig(ethernet),scenario=createBuilderScenario('BGP projection round trip',graph,'client','app',defaultBuilderLayout,addressing,routing,undefined,ethernet,createDefaultBuilderLinkProfiles(graph),createDefaultBuilderAclConfig(),createDefaultBuilderNatConfig(graph),dhcp,createDefaultBuilderIpv6Config(graph,addressing));
const restored=deserializeBuilderScenario(serializeBuilderScenario(scenario));assert.deepEqual(restored.routing.bgp,scenario.routing.bgp);assert.deepEqual(restored.graph,scenario.graph);assert.deepEqual(restored.addressing,scenario.addressing);assert.deepEqual(restored.ethernet,scenario.ethernet);assert.deepEqual(restored.linkProfiles,scenario.linkProfiles);assert.deepEqual(restored.acl,scenario.acl);assert.deepEqual(restored.nat,scenario.nat);assert.deepEqual(restored.dhcp,scenario.dhcp);assert.deepEqual(restored.ipv6,scenario.ipv6);
const restoredState=builderBgpState(restored.graph,restored.addressing,restored.routing.bgp),restoredProjection=projectBuilderBgpToAsGraph(restored.graph,restored.routing.bgp,restoredState,'edge',undefined,prefix);assert.deepEqual(restoredProjection.selectedPathAsns,projection.selectedPathAsns);assert.equal(restoredProjection.selectedRoute?.bestReason,projection.selectedRoute?.bestReason);
console.log('Builder BGP projection contract passed: exact selected path/attributes project to AS scale and the complete scenario/BGP truth round-trips unchanged.');
''',encoding='utf-8')

# Wire projection contract into normal check.
p=Path('package.json'); s=p.read_text(encoding='utf-8')
a='npm run test:builder-bgp-contract && npm run test:builder-ipv6-contract'
b='npm run test:builder-bgp-contract && npm run test:builder-bgp-projection-contract && npm run test:builder-ipv6-contract'
if s.count(a)!=1: raise SystemExit('package projection check anchor missing')
s=s.replace(a,b,1)
a='    "test:builder-bgp-contract": "node scripts/builder-bgp-contract-check.mjs",\n    "test:builder-ipv6-contract":'
b='    "test:builder-bgp-contract": "node scripts/builder-bgp-contract-check.mjs",\n    "test:builder-bgp-projection-contract": "node scripts/builder-bgp-projection-contract-check.mjs",\n    "test:builder-ipv6-contract":'
if s.count(a)!=1: raise SystemExit('package projection script anchor missing')
p.write_text(s.replace(a,b,1),encoding='utf-8')

# Mark final 11O roadmap item and docs complete.
p=Path('docs/ROADMAP.md'); s=p.read_text(encoding='utf-8')
old='- [ ] Builder BGP state can project into the Internet-scale AS view and back without changing truth'
new='- [x] Builder BGP state can project into the Internet-scale AS view and back without changing truth'
if s.count(old)!=1: raise SystemExit('roadmap BGP projection anchor missing')
p.write_text(s.replace(old,new,1),encoding='utf-8')

p=Path('docs/LAB11O.md'); s=p.read_text(encoding='utf-8')
old='''## Internet-scale projection\n\nThe BGP model already derives an AS-level projection from Builder ASNs and eBGP relationships. The follow-up 11O projection slice will carry that exact state into Lab 05 and back, preserving selected BGP path truth rather than asking the AS theater to recompute a different story.\n'''
new='''## Internet-scale projection\n\nThe BGP model derives an AS-level projection from the exact Builder ASN/session graph and the currently selected best BGP route. `OPEN AS PROJECTION` snapshots the complete schema-v9 Builder configuration and opens Lab 05 at AS scale with that selected path locked as display truth. Lab 05 does not run its own policy enumerator in projection mode, does not permit relationship failures or endpoint changes, and shows the Builder route attributes that produced the path.\n\n`RETURN TO BUILDER` reconstructs the Builder from the captured graph, layout, IPv4/IPv6 addressing, routing/BGP, Ethernet/VLAN, link profiles, ACL, NAT, and DHCP configuration. Session-only observations such as ARP, NAT translations, probe history, FDB entries, DHCP leases, and IPv6 lifecycle timers are intentionally not promoted into persisted truth just to make the cross-lab transition look stateful.\n'''
if s.count(old)!=1: raise SystemExit('LAB11O projection section anchor missing')
p.write_text(s.replace(old,new,1),encoding='utf-8')
print('Patched exact Builder BGP → Lab 05 → Builder projection bridge.')
