from pathlib import Path
import re, json

ROOT=Path(__file__).resolve().parents[1]
def read(path): return (ROOT/path).read_text(encoding='utf-8')
def write(path,text):
    p=ROOT/path; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(text,encoding='utf-8')
def replace_once(path,old,new):
    text=read(path); count=text.count(old)
    if count!=1: raise SystemExit(f'{path}: expected one match, found {count}: {old[:120]!r}')
    write(path,text.replace(old,new,1))
def regex_once(path,pattern,replacement,flags=0):
    text=read(path); out,count=re.subn(pattern,lambda _m:replacement,text,count=1,flags=flags)
    if count!=1: raise SystemExit(f'{path}: expected one regex match, found {count}: {pattern[:140]!r}')
    write(path,out)

# Probe result types can carry either routed family while preserving default IPv4 behavior.
probes='src/builder/probes.ts'
replace_once(probes,"export interface BuilderProbePacketSeed { id:string; label:string; sourceAddress:string; destinationAddress:string; sourceMac:string; destinationMac:string; ttl:number; }", "export interface BuilderProbePacketSeed { id:string; label:string; family:'ipv4'|'ipv6'; sourceAddress:string; destinationAddress:string; sourceMac:string; destinationMac:string; ttl:number; }")
replace_once(probes,"plane:'ROUTED IPV4';", "plane:'ROUTED IPV4'|'ROUTED IPV6';")
replace_once(probes,"return{id,label,sourceAddress,destinationAddress,sourceMac:stableMac(sourceNodeId,'probe'),destinationMac:stableMac(destinationNodeId,'probe'),ttl};", "return{id,label,family:'ipv4',sourceAddress,destinationAddress,sourceMac:stableMac(sourceNodeId,'probe'),destinationMac:stableMac(destinationNodeId,'probe'),ttl};")

# Packet microscope: use actual seeded IPv6 addresses instead of its old hard-coded pair.
packet='src/packet/model.ts'
replace_once(packet,"  sourceIpv4?: string;\n  destinationIpv4?: string;", "  sourceIpv4?: string;\n  destinationIpv4?: string;\n  sourceIpv6?: string;\n  destinationIpv6?: string;")
insert_parser=r'''function parseIpv6(value: string | undefined, fallback: readonly number[]): number[] {
  if (!value) return [...fallback];
  try {
    const normalized=value.trim().toLowerCase();
    if(!normalized||normalized.includes('%')||normalized.includes('.')||(normalized.match(/::/g)??[]).length>1)return[...fallback];
    const compressed=normalized.includes('::');
    const [leftText,rightText='']=compressed?normalized.split('::'):[normalized,''];
    const side=(text:string)=>text===''?[]:text.split(':').map((part)=>{if(!/^[0-9a-f]{1,4}$/.test(part))throw new Error('bad');return Number.parseInt(part,16);});
    const left=side(leftText),right=side(rightText);
    const groups=compressed?[...left,...Array.from({length:8-left.length-right.length},()=>0),...right]:left;
    if(groups.length!==8||(compressed&&8-left.length-right.length<1))return[...fallback];
    return groups.flatMap((group)=>[(group>>>8)&0xff,group&0xff]);
  } catch { return [...fallback]; }
}
'''
replace_once(packet,"export function hex16(value: number): string {", insert_parser+"export function hex16(value: number): string {")
replace_once(packet,"function buildIpv6(config: PacketConfig, transportLength: number): { bytes: number[]; checksum: null; fields: PacketField[] } {", "function buildIpv6(config: PacketConfig, transportLength: number, source: readonly number[], destination: readonly number[]): { bytes: number[]; checksum: null; fields: PacketField[] } {")
replace_once(packet,"  const bytes = [0x60,0,0,0,...word16(payloadLength),nextHeader,config.ttl,...SOURCE_IPV6,...DEST_IPV6];", "  const bytes = [0x60,0,0,0,...word16(payloadLength),nextHeader,config.ttl,...source,...destination];")
replace_once(packet,"    { id: 'ip6-src', label: 'Source', value: formatIpv6(SOURCE_IPV6), offset: 8, length: 16 },\n    { id: 'ip6-dst', label: 'Destination', value: formatIpv6(DEST_IPV6), offset: 24, length: 16 },", "    { id: 'ip6-src', label: 'Source', value: formatIpv6(source), offset: 8, length: 16 },\n    { id: 'ip6-dst', label: 'Destination', value: formatIpv6(destination), offset: 24, length: 16 },")
replace_once(packet,"function pseudoHeader(config: PacketConfig, transportLength: number, sourceIpv4: readonly number[], destinationIpv4: readonly number[]): number[] {", "function pseudoHeader(config: PacketConfig, transportLength: number, sourceIpv4: readonly number[], destinationIpv4: readonly number[], sourceIpv6: readonly number[], destinationIpv6: readonly number[]): number[] {")
replace_once(packet,"  return [...SOURCE_IPV6,...DEST_IPV6,...word32(transportLength + config.payloadBytes),0,0,0,protocol];", "  return [...sourceIpv6,...destinationIpv6,...word32(transportLength + config.payloadBytes),0,0,0,protocol];")
replace_once(packet,"function buildTransport(config: PacketConfig, payload: readonly number[], sourceIpv4: readonly number[], destinationIpv4: readonly number[]): { bytes: number[]; checksum: number; fields: PacketField[] } {", "function buildTransport(config: PacketConfig, payload: readonly number[], sourceIpv4: readonly number[], destinationIpv4: readonly number[], sourceIpv6: readonly number[], destinationIpv6: readonly number[]): { bytes: number[]; checksum: number; fields: PacketField[] } {")
replace_once(packet,"const checksumInput = config.family === 'ipv4' ? [...bytes, ...payload] : [...pseudoHeader(config, 8, sourceIpv4, destinationIpv4), ...bytes, ...payload];", "const checksumInput = config.family === 'ipv4' ? [...bytes, ...payload] : [...pseudoHeader(config, 8, sourceIpv4, destinationIpv4, sourceIpv6, destinationIpv6), ...bytes, ...payload];")
replace_once(packet,"let checksum = checksum16([...pseudoHeader(config, transportLength, sourceIpv4, destinationIpv4), ...bytes, ...payload]);", "let checksum = checksum16([...pseudoHeader(config, transportLength, sourceIpv4, destinationIpv4, sourceIpv6, destinationIpv6), ...bytes, ...payload]);")
replace_once(packet,"  const destinationIpv4 = parseIpv4(config.destinationIpv4, DEFAULT_DEST_IPV4);\n  const ethernet = buildEthernet(config);\n  const network = config.family === 'ipv4' ? buildIpv4(config, transportHeaderLength, sourceIpv4, destinationIpv4) : buildIpv6(config, transportHeaderLength);\n  const transport = buildTransport(config, payload, sourceIpv4, destinationIpv4);", "  const destinationIpv4 = parseIpv4(config.destinationIpv4, DEFAULT_DEST_IPV4);\n  const sourceIpv6 = parseIpv6(config.sourceIpv6, SOURCE_IPV6);\n  const destinationIpv6 = parseIpv6(config.destinationIpv6, DEST_IPV6);\n  const ethernet = buildEthernet(config);\n  const network = config.family === 'ipv4' ? buildIpv4(config, transportHeaderLength, sourceIpv4, destinationIpv4) : buildIpv6(config, transportHeaderLength, sourceIpv6, destinationIpv6);\n  const transport = buildTransport(config, payload, sourceIpv4, destinationIpv4, sourceIpv6, destinationIpv6);")

# App seeds packet microscope with the actual family and Builder addresses.
app='src/App.tsx'
old="initialConfig={builderPacketSeed ? { family: 'ipv4', transport: 'icmp', payloadBytes: 32, ttl: builderPacketSeed.ttl, sourceIpv4: builderPacketSeed.sourceAddress, destinationIpv4: builderPacketSeed.destinationAddress, sourceMac: builderPacketSeed.sourceMac, destinationMac: builderPacketSeed.destinationMac, icmpType: 8, icmpCode: 0, icmpSequence: Math.max(1, builderPacketSeed.ttl) } : undefined}\n            origin={builderPacketSeed ? { label: `LAB 11D · ${builderPacketSeed.label}`, timestamp: `TTL ${builderPacketSeed.ttl}`, actionLabel: 'RETURN TO BUILDER ↗' } : undefined}"
new="initialConfig={builderPacketSeed ? { family: builderPacketSeed.family, transport: 'icmp', payloadBytes: 32, ttl: builderPacketSeed.ttl, ...(builderPacketSeed.family === 'ipv4' ? { sourceIpv4: builderPacketSeed.sourceAddress, destinationIpv4: builderPacketSeed.destinationAddress } : { sourceIpv6: builderPacketSeed.sourceAddress, destinationIpv6: builderPacketSeed.destinationAddress }), sourceMac: builderPacketSeed.sourceMac, destinationMac: builderPacketSeed.destinationMac, icmpType: builderPacketSeed.family === 'ipv4' ? 8 : 128, icmpCode: 0, icmpSequence: Math.max(1, builderPacketSeed.ttl) } : undefined}\n            origin={builderPacketSeed ? { label: `${builderPacketSeed.family === 'ipv4' ? 'LAB 11D' : 'LAB 11N'} · ${builderPacketSeed.label}`, timestamp: `${builderPacketSeed.family === 'ipv4' ? 'TTL' : 'HOP LIMIT'} ${builderPacketSeed.ttl}`, actionLabel: 'RETURN TO BUILDER ↗' } : undefined}"
replace_once(app,old,new)

# Scenario v9 grows an optional/backward-compatible IPv6 field. Absent old v9 state stays disabled.
scenario='src/builder/scenario.ts'
replace_once(scenario,"import { cloneBuilderDhcpConfig, createDefaultBuilderDhcpConfig, createEmptyBuilderDhcpConfig, validateBuilderDhcpConfig, type BuilderDhcpConfig } from './dhcp.ts';", "import { cloneBuilderDhcpConfig, createDefaultBuilderDhcpConfig, createEmptyBuilderDhcpConfig, validateBuilderDhcpConfig, type BuilderDhcpConfig } from './dhcp.ts';\nimport { cloneBuilderIpv6Config, createDefaultBuilderIpv6Config, createEmptyBuilderIpv6Config, validateBuilderIpv6Config, type BuilderIpv6Config } from './ipv6.ts';")
replace_once(scenario,"export type BuilderScenarioV9=Omit<BuilderScenarioLegacyV8,'version'>&{version:9;dhcp:BuilderDhcpConfig};", "export type BuilderScenarioV9=Omit<BuilderScenarioLegacyV8,'version'>&{version:9;dhcp:BuilderDhcpConfig;ipv6:BuilderIpv6Config};")
replace_once(scenario,"if(!isRecord(raw.dhcp))throw new Error('Builder schema v9 requires DHCP configuration.');const ethernet=validateBuilderEthernetConfig(raw.ethernet as unknown as BuilderEthernetConfig);return{schema:'hopscotch.builder',version:9,name:assertString(raw.name,'Scenario name',80),graph,addressing,routing:validateBuilderRoutingConfig(graph,addressing,raw.routing as unknown as BuilderRoutingConfig),ethernet,linkProfiles:validateBuilderLinkProfiles(graph,raw.linkProfiles as unknown as BuilderLinkProfiles),acl:validateBuilderAclConfig(graph,raw.acl as unknown as BuilderAclConfig),nat:validateBuilderNatConfig(graph,raw.nat as unknown as BuilderNatConfig),dhcp:validateBuilderDhcpConfig(ethernet,raw.dhcp as unknown as BuilderDhcpConfig),sourceId", "if(!isRecord(raw.dhcp))throw new Error('Builder schema v9 requires DHCP configuration.');const ethernet=validateBuilderEthernetConfig(raw.ethernet as unknown as BuilderEthernetConfig);const ipv6=isRecord(raw.ipv6)?validateBuilderIpv6Config(graph,addressing,raw.ipv6 as unknown as BuilderIpv6Config):createEmptyBuilderIpv6Config(graph,addressing);return{schema:'hopscotch.builder',version:9,name:assertString(raw.name,'Scenario name',80),graph,addressing,routing:validateBuilderRoutingConfig(graph,addressing,raw.routing as unknown as BuilderRoutingConfig),ethernet,linkProfiles:validateBuilderLinkProfiles(graph,raw.linkProfiles as unknown as BuilderLinkProfiles),acl:validateBuilderAclConfig(graph,raw.acl as unknown as BuilderAclConfig),nat:validateBuilderNatConfig(graph,raw.nat as unknown as BuilderNatConfig),dhcp:validateBuilderDhcpConfig(ethernet,raw.dhcp as unknown as BuilderDhcpConfig),ipv6,sourceId")
old_sig="export function createBuilderScenario(name:string,graph:BuilderGraph,sourceId:string,destinationId:string,layout:BuilderLayout,addressing:BuilderAddressing=createDefaultBuilderAddressing(graph),routing:BuilderRoutingConfig=createDefaultBuilderRoutingConfig(),existing?:BuilderScenarioV9,ethernet:BuilderEthernetConfig=createDefaultBuilderEthernetConfig(),linkProfiles:BuilderLinkProfiles=createDefaultBuilderLinkProfiles(graph),acl:BuilderAclConfig=createDefaultBuilderAclConfig(),nat:BuilderNatConfig=createDefaultBuilderNatConfig(graph),dhcp:BuilderDhcpConfig=createDefaultBuilderDhcpConfig(ethernet)):BuilderScenarioV9{const now=new Date().toISOString();return validateV9({schema:'hopscotch.builder',version:9,name,graph:cloneBuilderGraph(graph),addressing,routing:cloneBuilderRoutingConfig(routing),ethernet:cloneBuilderEthernetConfig(ethernet),linkProfiles:cloneBuilderLinkProfiles(linkProfiles),acl:cloneBuilderAclConfig(acl),nat:cloneBuilderNatConfig(nat),dhcp:cloneBuilderDhcpConfig(dhcp),sourceId"
new_sig="export function createBuilderScenario(name:string,graph:BuilderGraph,sourceId:string,destinationId:string,layout:BuilderLayout,addressing:BuilderAddressing=createDefaultBuilderAddressing(graph),routing:BuilderRoutingConfig=createDefaultBuilderRoutingConfig(),existing?:BuilderScenarioV9,ethernet:BuilderEthernetConfig=createDefaultBuilderEthernetConfig(),linkProfiles:BuilderLinkProfiles=createDefaultBuilderLinkProfiles(graph),acl:BuilderAclConfig=createDefaultBuilderAclConfig(),nat:BuilderNatConfig=createDefaultBuilderNatConfig(graph),dhcp:BuilderDhcpConfig=createDefaultBuilderDhcpConfig(ethernet),ipv6:BuilderIpv6Config=createDefaultBuilderIpv6Config(graph,addressing)):BuilderScenarioV9{const now=new Date().toISOString();return validateV9({schema:'hopscotch.builder',version:9,name,graph:cloneBuilderGraph(graph),addressing,routing:cloneBuilderRoutingConfig(routing),ethernet:cloneBuilderEthernetConfig(ethernet),linkProfiles:cloneBuilderLinkProfiles(linkProfiles),acl:cloneBuilderAclConfig(acl),nat:cloneBuilderNatConfig(nat),dhcp:cloneBuilderDhcpConfig(dhcp),ipv6:cloneBuilderIpv6Config(ipv6),sourceId"
replace_once(scenario,old_sig,new_sig)

# Network Builder owns IPv6 state, reconciles it with topology/interface identity, saves/restores it, and can probe either family.
network='src/NetworkBuilder.tsx'
replace_once(network,"import { runBuilderProbe, type BuilderProbePacketSeed, type BuilderProbeResult } from './builder/probes.ts';", "import { runBuilderProbe, type BuilderProbePacketSeed, type BuilderProbeResult } from './builder/probes.ts';\nimport { runBuilderIpv6Probe } from './builder/ipv6-probes.ts';\nimport { cloneBuilderIpv6Config, createDefaultBuilderIpv6Config, reconcileBuilderIpv6Config, traceBuilderIpv6Forwarding, type BuilderIpv6Config } from './builder/ipv6.ts';")
replace_once(network,"import { BuilderOspfAreaPanel } from './BuilderOspfAreaPanel.tsx';", "import { BuilderOspfAreaPanel } from './BuilderOspfAreaPanel.tsx';\nimport { BuilderIpv6Panel } from './BuilderIpv6Panel.tsx';")
old_component="export function NetworkBuilder({ onExit, onOpenFailureStory, onOpenProbePacket, initialGraph = defaultBuilderGraph, initialLayout = defaultBuilderLayout, initialAddressing, initialRouting, initialEthernet, initialNat, initialSourceId = 'client', initialDestinationId = 'app', stressLabel }: { onExit: () => void; onOpenFailureStory: () => void; onOpenProbePacket?: (seed: BuilderProbePacketSeed) => void; initialGraph?: BuilderGraph; initialLayout?: BuilderLayout; initialAddressing?: BuilderAddressing; initialRouting?: BuilderRoutingConfig; initialEthernet?: BuilderEthernetConfig; initialNat?: BuilderNatConfig; initialSourceId?: string; initialDestinationId?: string; stressLabel?: string }) {"
new_component="export function NetworkBuilder({ onExit, onOpenFailureStory, onOpenProbePacket, initialGraph = defaultBuilderGraph, initialLayout = defaultBuilderLayout, initialAddressing, initialRouting, initialEthernet, initialNat, initialIpv6, initialSourceId = 'client', initialDestinationId = 'app', stressLabel }: { onExit: () => void; onOpenFailureStory: () => void; onOpenProbePacket?: (seed: BuilderProbePacketSeed) => void; initialGraph?: BuilderGraph; initialLayout?: BuilderLayout; initialAddressing?: BuilderAddressing; initialRouting?: BuilderRoutingConfig; initialEthernet?: BuilderEthernetConfig; initialNat?: BuilderNatConfig; initialIpv6?: BuilderIpv6Config; initialSourceId?: string; initialDestinationId?: string; stressLabel?: string }) {"
replace_once(network,old_component,new_component)
replace_once(network,"  const [routing, setRouting] = useState<BuilderRoutingConfig>(() => cloneBuilderRoutingConfig(initialRouting ?? createDefaultBuilderRoutingConfig()));", "  const [routing, setRouting] = useState<BuilderRoutingConfig>(() => cloneBuilderRoutingConfig(initialRouting ?? createDefaultBuilderRoutingConfig()));\n  const [ipv6, setIpv6] = useState<BuilderIpv6Config>(() => { const initialIpv4=initialAddressing ?? createDefaultBuilderAddressing(initialGraph); return cloneBuilderIpv6Config(initialIpv6 ?? createDefaultBuilderIpv6Config(initialGraph,initialIpv4,!stressLabel)); });")
replace_once(network,"  const [selectedProbeAttempt, setSelectedProbeAttempt] = useState(0);", "  const [selectedProbeAttempt, setSelectedProbeAttempt] = useState(0);\n  const [probeFamily, setProbeFamily] = useState<'ipv4'|'ipv6'>('ipv4');")
replace_once(network,"  const forwardingTrace = useMemo(() => traceBuilderForwarding(graph, addressing, routing, sourceId, destinationId), [graph, addressing, routing, sourceId, destinationId]);", "  const forwardingTrace = useMemo(() => traceBuilderForwarding(graph, addressing, routing, sourceId, destinationId), [graph, addressing, routing, sourceId, destinationId]);\n  const ipv6ForwardingTrace = useMemo(() => traceBuilderIpv6Forwarding(graph, ipv6, sourceId, destinationId), [graph, ipv6, sourceId, destinationId]);")
old_run="  const runProbe = (kind: 'ping' | 'traceroute') => {\n    const result = runBuilderProbe(graph, addressing, routing, kind, sourceId, destinationId, probeHistory.length + 1, linkProfiles, acl, nat, natSessions);\n    setNatSessions(result.natSessions);"
new_run="  const runProbe = (kind: 'ping' | 'traceroute') => {\n    const result = probeFamily === 'ipv6' ? runBuilderIpv6Probe(graph, ipv6, kind, sourceId, destinationId, probeHistory.length + 1, linkProfiles, natSessions) : runBuilderProbe(graph, addressing, routing, kind, sourceId, destinationId, probeHistory.length + 1, linkProfiles, acl, nat, natSessions);\n    setNatSessions(result.natSessions);"
replace_once(network,old_run,new_run)
replace_once(network,"    setRouting(nextRouting);\n    setLinkProfiles(reconcileBuilderLinkProfiles(next, linkProfiles));", "    setRouting(nextRouting);\n    setIpv6(reconcileBuilderIpv6Config(next,nextAddressing,ipv6));\n    setLinkProfiles(reconcileBuilderLinkProfiles(next, linkProfiles));")
replace_once(network,"  const commitAddressing = (next: BuilderAddressing) => {\n    setAddressing(next);\n    setRouting(reconcileBuilderRoutingConfig(graph, next, routing));", "  const commitAddressing = (next: BuilderAddressing) => {\n    setAddressing(next);\n    setRouting(reconcileBuilderRoutingConfig(graph, next, routing));\n    setIpv6(reconcileBuilderIpv6Config(graph,next,ipv6));")
replace_once(network,"    setRouting(cloneBuilderRoutingConfig(initialRouting ?? createDefaultBuilderRoutingConfig()));\n    setEthernet", "    setRouting(cloneBuilderRoutingConfig(initialRouting ?? createDefaultBuilderRoutingConfig()));\n    { const initialIpv4=initialAddressing ?? createDefaultBuilderAddressing(initialGraph); setIpv6(cloneBuilderIpv6Config(initialIpv6 ?? createDefaultBuilderIpv6Config(initialGraph,initialIpv4,!stressLabel))); }\n    setEthernet")
# Save/export: preserve DHCP default parameter while passing IPv6 in the new last slot. Fix stale schema copy while here.
replace_once(network,"createBuilderScenario(scenarioName.trim() || 'Untitled topology', graph, sourceId, destinationId, layout, addressing, routing, existing, ethernet, linkProfiles, acl, nat);", "createBuilderScenario(scenarioName.trim() || 'Untitled topology', graph, sourceId, destinationId, layout, addressing, routing, existing, ethernet, linkProfiles, acl, nat, undefined, ipv6);")
replace_once(network,"setMessage(`Saved “${scenario.name}” locally as Builder schema v8.`);", "setMessage(`Saved “${scenario.name}” locally as Builder schema v${scenario.version}.`);")
replace_once(network,"setGraph(cloneBuilderGraph(scenario.graph)); setAddressing(cloneBuilderAddressing(scenario.addressing)); setRouting(cloneBuilderRoutingConfig(scenario.routing));", "setGraph(cloneBuilderGraph(scenario.graph)); setAddressing(cloneBuilderAddressing(scenario.addressing)); setRouting(cloneBuilderRoutingConfig(scenario.routing)); setIpv6(cloneBuilderIpv6Config(scenario.ipv6));")
replace_once(network,"Routing, link characteristics, ACL/NAT, VLAN, and STP configuration restored; session ARP/NAT/probe state cleared.", "IPv4/IPv6 routing, link characteristics, ACL/NAT, VLAN, and STP configuration restored; session ARP/NAT/probe state cleared.")
replace_once(network,"createBuilderScenario(scenarioName.trim() || 'Exported topology', graph, sourceId, destinationId, layout, addressing, routing, undefined, ethernet, linkProfiles, acl, nat);", "createBuilderScenario(scenarioName.trim() || 'Exported topology', graph, sourceId, destinationId, layout, addressing, routing, undefined, ethernet, linkProfiles, acl, nat, undefined, ipv6);")
replace_once(network,"setMessage('Scenario v8 exported with routed topology, link characteristics, ACL/NAT policy, and Ethernet/STP configuration; ARP/NAT-session/probe/FDB observations remain session-only.');", "setMessage('Scenario v9 exported with dual-stack routed topology, link characteristics, ACL/NAT policy, and Ethernet/STP configuration; ARP/NAT-session/probe/FDB observations remain session-only.');")
# Probe family selector and labels. Keep IPv4 default so old browser contracts are unchanged.
old_probe='<section className="builder-probe-section"><div className="control-title"><span>ACTIVE PROBES</span><strong>ICMP · SESSION ONLY</strong></div><div className="button-row"><button type="button" onClick={()=>runProbe(\'ping\')}>PING</button><button type="button" onClick={()=>runProbe(\'traceroute\')}>TRACEROUTE</button><button type="button" onClick={()=>{setProbeHistory([]);setSelectedProbeId(null);setSelectedProbeAttempt(0);}}>CLEAR</button></div>'
new_probe='<section className="builder-probe-section"><div className="control-title"><span>ACTIVE PROBES</span><strong>{probeFamily===\'ipv6\'?\'ICMPV6\':\'ICMP\'} · SESSION ONLY</strong></div><label>NETWORK FAMILY<select value={probeFamily} onChange={(event)=>setProbeFamily(event.currentTarget.value as \'ipv4\'|\'ipv6\')}><option value="ipv4">IPV4</option><option value="ipv6" disabled={!ipv6.enabled}>IPV6{ipv6.enabled?\'\':\' · DISABLED\'}</option></select></label><div className="button-row"><button type="button" onClick={()=>runProbe(\'ping\')}>PING</button><button type="button" onClick={()=>runProbe(\'traceroute\')}>TRACEROUTE</button><button type="button" onClick={()=>{setProbeHistory([]);setSelectedProbeId(null);setSelectedProbeAttempt(0);}}>CLEAR</button></div>'
replace_once(network,old_probe,new_probe)
replace_once(network,"{probe.sequence}. {probe.kind.toUpperCase()} · {probe.success?'PASS':'FAIL'}{probe.natApplied?' · NAT':''}", "{probe.sequence}. {probe.kind.toUpperCase()} · {probe.plane==='ROUTED IPV6'?'IPV6':'IPV4'} · {probe.success?'PASS':'FAIL'}{probe.natApplied?' · NAT':''}")
replace_once(network,"<label>TTL / ATTEMPT><select", "<label>{selectedProbe.plane==='ROUTED IPV6'?'HOP LIMIT / ATTEMPT':'TTL / ATTEMPT'}<select") if False else None
# Literal JSX is minified without the accidental > in the label text.
replace_once(network,"<label>TTL / ATTEMPT<select value={Math.min(selectedProbeAttempt,selectedProbe.attempts.length-1)}", "<label>{selectedProbe.plane==='ROUTED IPV6'?'HOP LIMIT / ATTEMPT':'TTL / ATTEMPT'}<select value={Math.min(selectedProbeAttempt,selectedProbe.attempts.length-1)}")
replace_once(network,"<small className=\"builder-routing-note\">PING validates request + reply paths. TRACEROUTE expires TTL at routers and needs a reverse route for each Time Exceeded response. ACTIVE NAT BOUNDARIES USE THE SAME SESSION TABLE · RTT COMES FROM LINK LATENCY, NEVER ROUTING COST.</small>", "<small className=\"builder-routing-note\">{probeFamily==='ipv6'?'IPV6 USES AN INDEPENDENT IPV6 FIB · HOP LIMIT EXPIRES AT ROUTERS · EACH ICMPV6 RESPONSE NEEDS A REVERSE IPV6 ROUTE · ND / PTB / IPV6 POLICY ARE DEFERRED.':'PING VALIDATES REQUEST + REPLY PATHS · TRACEROUTE EXPIRES TTL AT ROUTERS · ACTIVE NAT BOUNDARIES USE THE SAME SESSION TABLE.'} RTT COMES FROM LINK LATENCY, NEVER ROUTING COST.</small>")
# Mount IPv6 controls beside IPv4 L3 controls, but keep stress fixture DOM unchanged.
anchor='<section className="builder-device-section"><div className="control-title"><span>SELECTED DEVICE</span>'
insert='{!stressLabel&&<BuilderIpv6Panel graph={graph} ipv4={addressing} ipv6={ipv6} selectedNodeId={selectedNodeId} selectedLinkId={selectedLinkId} sourceId={sourceId} destinationId={destinationId} onChange={setIpv6} onMessage={setMessage}/>}\n          '+anchor
replace_once(network,anchor,insert)
replace_once(network,"<section><div className=\"control-title\"><span>SCENARIOS</span><strong>SCHEMA V8 · ROUTED + LAN + POLICY + NAT</strong></div>", "<section><div className=\"control-title\"><span>SCENARIOS</span><strong>SCHEMA V9 · DUAL STACK + LAN + POLICY</strong></div>")
# Stage forwarding copy: add explicit IPv6 status without changing IPv4 highlighting semantics.
replace_once(network,"  const forwardingLinks = new Set(forwardingTrace.hops.flatMap((hop) => hop.linkId ? [hop.linkId] : []));", "  const forwardingLinks = new Set(forwardingTrace.hops.flatMap((hop) => hop.linkId ? [hop.linkId] : []));\n  const ipv6ForwardingLinks = new Set(ipv6ForwardingTrace.hops.flatMap((hop) => hop.linkId ? [hop.linkId] : []));")

# Wire permanent contract and roadmap.
package='package.json'
text=read(package)
text=text.replace('npm run test:builder-ospf-multiarea-contract && npm run test:builder-probes-contract','npm run test:builder-ospf-multiarea-contract && npm run test:builder-ipv6-contract && npm run test:builder-probes-contract')
text=text.replace('"test:builder-ospf-multiarea-contract": "node scripts/builder-ospf-multiarea-contract-check.mjs"','"test:builder-ospf-multiarea-contract": "node scripts/builder-ospf-multiarea-contract-check.mjs",\n    "test:builder-ipv6-contract": "node scripts/builder-ipv6-contract-check.mjs"')
write(package,text)
roadmap='docs/ROADMAP.md'
replace_once(roadmap,'- [ ] IPv6 global and link-local interface addressing','- [x] IPv6 global and link-local interface addressing')
replace_once(roadmap,'- [ ] IPv6 connected/static forwarding and default routes','- [x] IPv6 connected/static forwarding and default routes')
replace_once(roadmap,'- [ ] dual-stack application/probe selection keeps IPv4 and IPv6 truth independent','- [x] dual-stack application/probe selection keeps IPv4 and IPv6 truth independent')

print('Lab 11N IPv6 integration patch applied.')
