from pathlib import Path


def replace(path: str, old: str, new: str):
    p = Path(path)
    text = p.read_text()
    if old not in text:
        raise SystemExit(f'needle not found in {path}: {old[:120]!r}')
    p.write_text(text.replace(old, new, 1))

# Ethernet: additive enterprise fields stay inside the existing canonical fabric.
p = Path('src/builder/ethernet.ts')
text = p.read_text()
text = text.replace("import { builderStpState, cloneBuilderStpConfig, createDefaultBuilderStpConfig, validateBuilderStpConfig, type BuilderStpConfig } from './stp.ts';\n", "import { builderStpState, cloneBuilderStpConfig, createDefaultBuilderStpConfig, validateBuilderStpConfig, type BuilderStpConfig } from './stp.ts';\nimport { builderEthernetLogicalLinkCarriesVlan } from './ethernet-link.ts';\n")
text = text.replace("export type BuilderEthernetDeviceKind = 'endpoint' | 'switch' | 'router';\nexport type BuilderEthernetPortMode = 'access' | 'trunk';", "export type BuilderEthernetDeviceKind = 'endpoint' | 'switch' | 'l3-switch' | 'router';\nexport type BuilderEthernetPortMode = 'access' | 'trunk' | 'routed';")
text = text.replace("export interface BuilderEthernetInterface {\n  vlanId: number;\n  address: string;\n  gateway?: string | null;\n}", "export interface BuilderEthernetInterface {\n  vlanId: number;\n  address: string;\n  gateway?: string | null;\n  vrfId?: string;\n  virtualGateway?: string | null;\n  gatewayPriority?: number;\n}")
text = text.replace("export interface BuilderEthernetLink {\n  id: string;\n  a: string;\n  b: string;\n  mode: BuilderEthernetPortMode;\n  accessVlan?: number;\n  allowedVlans?: number[];\n  failed: boolean;\n}", "export interface BuilderEthernetLink {\n  id: string;\n  a: string;\n  b: string;\n  mode: BuilderEthernetPortMode;\n  accessVlan?: number;\n  allowedVlans?: number[];\n  nativeVlanA?: number | null;\n  nativeVlanB?: number | null;\n  bundleId?: string | null;\n  bundleProtocol?: 'lacp' | 'static';\n  routedAAddress?: string | null;\n  routedBAddress?: string | null;\n  routedPrefixLength?: number | null;\n  vrfId?: string | null;\n  failed: boolean;\n}\n\nexport interface BuilderEthernetVrfStaticRoute {\n  id: string;\n  deviceId: string;\n  vrfId: string;\n  prefix: string;\n  nextHopDeviceId: string;\n  linkId: string;\n}")
text = text.replace("export interface BuilderEthernetConfig {\n  vlans: BuilderEthernetVlan[];\n  devices: BuilderEthernetDevice[];\n  links: BuilderEthernetLink[];\n  layout: Record<string, BuilderEthernetPoint>;\n  stp: BuilderStpConfig;\n}", "export interface BuilderEthernetConfig {\n  vlans: BuilderEthernetVlan[];\n  devices: BuilderEthernetDevice[];\n  links: BuilderEthernetLink[];\n  layout: Record<string, BuilderEthernetPoint>;\n  stp: BuilderStpConfig;\n  vrfStaticRoutes?: BuilderEthernetVrfStaticRoute[];\n}")
text = text.replace("    stp: cloneBuilderStpConfig(config.stp),\n  };", "    stp: cloneBuilderStpConfig(config.stp),\n    vrfStaticRoutes: config.vrfStaticRoutes?.map((route) => ({ ...route })) ?? [],\n  };")
text = text.replace("  return { vlans: [], devices: [], links: [], layout: {}, stp: createDefaultBuilderStpConfig() };", "  return { vlans: [], devices: [], links: [], layout: {}, stp: createDefaultBuilderStpConfig(), vrfStaticRoutes: [] };")
text = text.replace("function validCidr(value: string): boolean {\n  const [address, prefix] = value.split('/');\n  return Boolean(address && validIpv4(address) && /^\\d{1,2}$/.test(prefix ?? '') && Number(prefix) >= 8 && Number(prefix) <= 30);\n}", "function validCidr(value: string): boolean {\n  const [address, prefix] = value.split('/');\n  return Boolean(address && validIpv4(address) && /^\\d{1,2}$/.test(prefix ?? '') && Number(prefix) >= 8 && Number(prefix) <= 30);\n}\nfunction validRouteCidr(value: string): boolean {\n  const [address, prefix, ...extra] = value.split('/');\n  return extra.length === 0 && Boolean(address && validIpv4(address) && /^\\d{1,2}$/.test(prefix ?? '') && Number(prefix) >= 0 && Number(prefix) <= 32);\n}\nfunction validVrfId(value: string | null | undefined): boolean { return value == null || /^[A-Za-z0-9_.-]{1,24}$/.test(value.trim()); }\nfunction layer3Kind(kind: BuilderEthernetDeviceKind): boolean { return kind === 'router' || kind === 'l3-switch'; }\nfunction switchingKind(kind: BuilderEthernetDeviceKind): boolean { return kind === 'switch' || kind === 'l3-switch'; }\nfunction ifaceVrf(iface: BuilderEthernetInterface): string { return iface.vrfId?.trim().toUpperCase() || 'DEFAULT'; }")
text = text.replace("    if (!device.label || device.label.length > 32 || !['endpoint','switch','router'].includes(device.kind) || !MAC_RE.test(device.mac)) throw new Error(`Ethernet device ${device.id} metadata is invalid.`);", "    if (!device.label || device.label.length > 32 || !['endpoint','switch','l3-switch','router'].includes(device.kind) || !MAC_RE.test(device.mac)) throw new Error(`Ethernet device ${device.id} metadata is invalid.`);")
text = text.replace("      if (!vlanIds.has(iface.vlanId) || localVlans.has(iface.vlanId) || !validIpv4(iface.address) || (iface.gateway != null && !validIpv4(iface.gateway))) throw new Error(`Ethernet interface on ${device.id} is invalid.`);\n      localVlans.add(iface.vlanId);", "      if (!vlanIds.has(iface.vlanId) || localVlans.has(iface.vlanId) || !validIpv4(iface.address) || (iface.gateway != null && !validIpv4(iface.gateway)) || (iface.virtualGateway != null && !validIpv4(iface.virtualGateway)) || !validVrfId(iface.vrfId) || (iface.gatewayPriority != null && (!Number.isInteger(iface.gatewayPriority) || iface.gatewayPriority < 1 || iface.gatewayPriority > 255))) throw new Error(`Ethernet interface on ${device.id} is invalid.`);\n      localVlans.add(iface.vlanId);")
text = text.replace("  const pairs = new Set<string>();\n", "")
text = text.replace("    const pair = [link.a, link.b].sort().join('|');\n    if (pairs.has(pair)) throw new Error(`Duplicate Ethernet link ${pair}.`);\n    pairs.add(pair); linkIds.add(link.id);", "    linkIds.add(link.id);")
old_link_validation = """    if (link.mode === 'access') {\n      if (!Number.isInteger(link.accessVlan) || !vlanIds.has(link.accessVlan!)) throw new Error(`Access link ${link.id} needs an existing VLAN.`);\n    } else if (link.mode === 'trunk') {\n      if (a.kind === 'endpoint' || b.kind === 'endpoint') throw new Error(`Endpoint links cannot be trunks (${link.id}).`);\n      const allowed = [...new Set(link.allowedVlans ?? [])].sort((x,y)=>x-y);\n      if (allowed.length === 0 || allowed.some((id) => !vlanIds.has(id))) throw new Error(`Trunk ${link.id} must allow at least one existing VLAN.`);\n    } else throw new Error(`Ethernet link ${link.id} mode must be access or trunk.`);\n"""
new_link_validation = """    if (link.mode === 'access') {\n      if (!Number.isInteger(link.accessVlan) || !vlanIds.has(link.accessVlan!)) throw new Error(`Access link ${link.id} needs an existing VLAN.`);\n      if (link.bundleId) throw new Error(`Access link ${link.id} cannot be an EtherChannel member in this bounded enterprise slice.`);\n    } else if (link.mode === 'trunk') {\n      if (a.kind === 'endpoint' || b.kind === 'endpoint') throw new Error(`Endpoint links cannot be trunks (${link.id}).`);\n      const allowed = [...new Set(link.allowedVlans ?? [])].sort((x,y)=>x-y);\n      if (allowed.length === 0 || allowed.some((id) => !vlanIds.has(id))) throw new Error(`Trunk ${link.id} must allow at least one existing VLAN.`);\n      for (const native of [link.nativeVlanA, link.nativeVlanB]) if (native != null && (!Number.isInteger(native) || !allowed.includes(native))) throw new Error(`Trunk ${link.id} native VLAN must be one of its allowed VLANs.`);\n      if (link.bundleId != null && !/^[A-Za-z0-9_.-]{1,32}$/.test(link.bundleId)) throw new Error(`Trunk ${link.id} has an invalid bundle id.`);\n      if (link.bundleProtocol != null && !link.bundleId) throw new Error(`Trunk ${link.id} cannot set a bundle protocol without a bundle id.`);\n      if (link.bundleProtocol != null && !['lacp','static'].includes(link.bundleProtocol)) throw new Error(`Trunk ${link.id} bundle protocol is invalid.`);\n    } else if (link.mode === 'routed') {\n      if (!layer3Kind(a.kind) || !layer3Kind(b.kind)) throw new Error(`Routed link ${link.id} must connect router or Layer-3-switch devices.`);\n      if (!validIpv4(link.routedAAddress ?? '') || !validIpv4(link.routedBAddress ?? '') || !Number.isInteger(link.routedPrefixLength) || link.routedPrefixLength! < 8 || link.routedPrefixLength! > 31 || !validVrfId(link.vrfId)) throw new Error(`Routed link ${link.id} requires valid endpoint addresses, /8–/31 prefix length, and VRF id.`);\n      if (link.bundleId || link.accessVlan != null || link.allowedVlans?.length) throw new Error(`Routed link ${link.id} cannot simultaneously carry switched VLAN or bundle semantics.`);\n    } else throw new Error(`Ethernet link ${link.id} mode must be access, trunk, or routed.`);\n"""
if old_link_validation not in text: raise SystemExit('ethernet link validation needle not found')
text = text.replace(old_link_validation, new_link_validation, 1)
needle = """  for (const device of input.devices) {\n    const point = input.layout[device.id];\n"""
insert = """  const bundles = new Map<string, BuilderEthernetLink[]>();\n  for (const link of input.links) if (link.bundleId) { const members = bundles.get(link.bundleId) ?? []; members.push(link); bundles.set(link.bundleId, members); }\n  for (const [bundleId, members] of bundles) {\n    const first = members[0]!; const pair = [first.a, first.b].sort().join('|');\n    if (members.length < 2 || members.some((member) => [member.a, member.b].sort().join('|') !== pair || member.mode !== 'trunk' || member.bundleProtocol !== first.bundleProtocol || JSON.stringify([...(member.allowedVlans ?? [])].sort((a,b)=>a-b)) !== JSON.stringify([...(first.allowedVlans ?? [])].sort((a,b)=>a-b)) || member.nativeVlanA !== first.nativeVlanA || member.nativeVlanB !== first.nativeVlanB)) throw new Error(`EtherChannel ${bundleId} members must be parallel trunk links with identical VLAN/native/protocol configuration.`);\n  }\n  const vrfStaticRoutes: BuilderEthernetVrfStaticRoute[] = []; const vrfRouteIds = new Set<string>();\n  for (const route of input.vrfStaticRoutes ?? []) {\n    if (!route.id || vrfRouteIds.has(route.id) || !/^[A-Za-z0-9_.:-]{1,80}$/.test(route.id)) throw new Error(`Enterprise VRF static route id ${route.id} is invalid or duplicated.`);\n    vrfRouteIds.add(route.id);\n    const device = input.devices.find((entry) => entry.id === route.deviceId); const nextHop = input.devices.find((entry) => entry.id === route.nextHopDeviceId); const link = input.links.find((entry) => entry.id === route.linkId);\n    if (!device || !nextHop || !layer3Kind(device.kind) || !layer3Kind(nextHop.kind) || !validVrfId(route.vrfId) || !validRouteCidr(route.prefix) || !link || link.mode !== 'routed' || !((link.a === route.deviceId && link.b === route.nextHopDeviceId) || (link.b === route.deviceId && link.a === route.nextHopDeviceId)) || (link.vrfId?.trim().toUpperCase() || 'DEFAULT') !== route.vrfId.trim().toUpperCase()) throw new Error(`Enterprise VRF static route ${route.id} must use a directly connected routed port in the same VRF.`);\n    vrfStaticRoutes.push({ ...route, vrfId: route.vrfId.trim().toUpperCase() });\n  }\n\n  for (const device of input.devices) {\n    const point = input.layout[device.id];\n"""
if needle not in text: raise SystemExit('layout needle not found')
text = text.replace(needle, insert, 1)
text = text.replace("  const normalized = cloneBuilderEthernetConfig({ ...input, stp: cloneBuilderStpConfig(input.stp) });", "  const normalized = cloneBuilderEthernetConfig({ ...input, stp: cloneBuilderStpConfig(input.stp), vrfStaticRoutes });")
text = text.replace("function linkCarriesVlanRaw(link: BuilderEthernetLink, vlanId: number): boolean {\n  if (link.failed) return false;\n  return link.mode === 'access' ? link.accessVlan === vlanId : Boolean(link.allowedVlans?.includes(vlanId));\n}\n\nfunction linkCarriesVlan(config: BuilderEthernetConfig, link: BuilderEthernetLink, vlanId: number): boolean {\n  if (!linkCarriesVlanRaw(link, vlanId)) return false;", "function linkCarriesVlanRaw(config: BuilderEthernetConfig, link: BuilderEthernetLink, vlanId: number): boolean {\n  return builderEthernetLogicalLinkCarriesVlan(config.links, link, vlanId);\n}\n\nfunction linkCarriesVlan(config: BuilderEthernetConfig, link: BuilderEthernetLink, vlanId: number): boolean {\n  if (!linkCarriesVlanRaw(config, link, vlanId)) return false;")
text = text.replace("      if (nextDevice.kind !== 'switch') continue;", "      if (!switchingKind(nextDevice.kind)) continue;")
text = text.replace("    if (device?.kind !== 'switch' || index === 0) return;", "    if (!device || !switchingKind(device.kind) || index === 0) return;")
old_router = """  const router = config.devices.filter((device) => device.kind==='router' && interfaceFor(device,sourceVlan) && interfaceFor(device,destinationVlan)).sort((a,b)=>a.id.localeCompare(b.id))[0];\n  if (!router) return fail(sourceId,destinationId,sourceVlan,destinationVlan,`VLAN ${sourceVlan} and VLAN ${destinationVlan} are isolated: no router has interfaces in both broadcast domains.`);\n  const sourceRouterIf = interfaceFor(router,sourceVlan)!; const destinationRouterIf = interfaceFor(router,destinationVlan)!;\n  if (sourceIf.gateway !== sourceRouterIf.address) return fail(sourceId,destinationId,sourceVlan,destinationVlan,`${source.label} gateway ${sourceIf.gateway ?? 'NONE'} does not match ${router.label} VLAN ${sourceVlan} interface ${sourceRouterIf.address}.`);\n  if (destinationIf.gateway !== destinationRouterIf.address) return fail(sourceId,destinationId,sourceVlan,destinationVlan,`${destination.label} gateway ${destinationIf.gateway ?? 'NONE'} does not match ${router.label} VLAN ${destinationVlan} interface ${destinationRouterIf.address}.`);\n"""
new_router = """  const routerCandidates = config.devices.filter((device) => layer3Kind(device.kind) && interfaceFor(device,sourceVlan) && interfaceFor(device,destinationVlan)).flatMap((device) => { const sourceRouterIf=interfaceFor(device,sourceVlan)!; const destinationRouterIf=interfaceFor(device,destinationVlan)!; if(ifaceVrf(sourceRouterIf)!==ifaceVrf(destinationRouterIf))return []; if(sourceIf.gateway!==sourceRouterIf.address&&sourceIf.gateway!==sourceRouterIf.virtualGateway)return []; if(destinationIf.gateway!==destinationRouterIf.address&&destinationIf.gateway!==destinationRouterIf.virtualGateway)return []; return [{device,sourceRouterIf,destinationRouterIf}]; }).sort((a,b)=>(b.sourceRouterIf.gatewayPriority??100)-(a.sourceRouterIf.gatewayPriority??100)||a.device.id.localeCompare(b.device.id));\n  const candidate = routerCandidates.find(({device})=>builderEthernetPathForVlan(config,sourceId,device.id,sourceVlan)!==null);\n  if (!candidate) return fail(sourceId,destinationId,sourceVlan,destinationVlan,`VLAN ${sourceVlan} and VLAN ${destinationVlan} are isolated in the current VRF/gateway state: no reachable Layer-3 device owns both broadcast domains.`);\n  const router=candidate.device; const sourceRouterIf=candidate.sourceRouterIf; const destinationRouterIf=candidate.destinationRouterIf;\n"""
if old_router not in text: raise SystemExit('router flow needle not found')
text = text.replace(old_router, new_router, 1)
text = text.replace("summary:`${router.label} routes VLAN ${sourceVlan} → VLAN ${destinationVlan} using connected router-on-a-stick subinterfaces; IP TTL decreases once at the router.`", "summary:`${router.label} routes VLAN ${sourceVlan} → VLAN ${destinationVlan} in VRF ${ifaceVrf(sourceRouterIf)} using connected ${router.kind==='l3-switch'?'SVIs':'router interfaces'}; IP TTL decreases once at the Layer-3 boundary.`")
p.write_text(text)

# STP: preserve legacy steady state while adding RSTP mode and treating L3 switches / bundles as switching truth.
p = Path('src/builder/stp.ts')
text = p.read_text()
text = text.replace("import type { BuilderEthernetConfig, BuilderEthernetDevice, BuilderEthernetLink } from './ethernet.ts';", "import type { BuilderEthernetConfig, BuilderEthernetDevice, BuilderEthernetLink } from './ethernet.ts';\nimport { builderEthernetLogicalLinkCarriesVlan } from './ethernet-link.ts';")
text = text.replace("export interface BuilderStpConfig {\n  enabled: boolean;\n  bridgePriorities: Record<string, number>;\n}", "export interface BuilderStpConfig {\n  enabled: boolean;\n  protocol?: 'stp' | 'rstp';\n  bridgePriorities: Record<string, number>;\n}")
text = text.replace("export function cloneBuilderStpConfig(config: BuilderStpConfig | undefined): BuilderStpConfig { return { enabled: config?.enabled !== false, bridgePriorities: { ...(config?.bridgePriorities ?? {}) } }; }", "export function cloneBuilderStpConfig(config: BuilderStpConfig | undefined): BuilderStpConfig { return { enabled: config?.enabled !== false, ...(config?.protocol ? { protocol: config.protocol } : {}), bridgePriorities: { ...(config?.bridgePriorities ?? {}) } }; }")
text = text.replace("function carriesVlan(link: BuilderEthernetLink, vlanId: number): boolean {\n  if (link.failed) return false;\n  return link.mode === 'access' ? link.accessVlan === vlanId : Boolean(link.allowedVlans?.includes(vlanId));\n}", "function carriesVlan(config: BuilderEthernetConfig, link: BuilderEthernetLink, vlanId: number): boolean { return builderEthernetLogicalLinkCarriesVlan(config.links, link, vlanId); }")
text = text.replace("function switchIds(config: BuilderEthernetConfig): string[] { return config.devices.filter((device)=>device.kind==='switch').map((device)=>device.id).sort(); }", "function switchIds(config: BuilderEthernetConfig): string[] { return config.devices.filter((device)=>device.kind==='switch'||device.kind==='l3-switch').map((device)=>device.id).sort(); }")
text = text.replace("  return { enabled: next.enabled, bridgePriorities: priorities };", "  if(next.protocol!=null&&!['stp','rstp'].includes(next.protocol))throw new Error('Spanning-tree protocol must be stp or rstp.');\n  return { enabled: next.enabled, ...(next.protocol ? {protocol:next.protocol}:{}), bridgePriorities: priorities };")
text = text.replace("    if(!carriesVlan(link,vlanId))return false;\n    return deviceById(config,link.a)?.kind==='switch'&&deviceById(config,link.b)?.kind==='switch';", "    if(!carriesVlan(config,link,vlanId))return false;\n    const a=deviceById(config,link.a)?.kind,b=deviceById(config,link.b)?.kind; return (a==='switch'||a==='l3-switch')&&(b==='switch'||b==='l3-switch');")
text = text.replace("      const aSwitch=deviceById(config,link.a)?.kind==='switch',bSwitch=deviceById(config,link.b)?.kind==='switch';\n      if(!aSwitch||!bSwitch||!carriesVlan(link,vlanId))", "      const aKind=deviceById(config,link.a)?.kind,bKind=deviceById(config,link.b)?.kind; const aSwitch=aKind==='switch'||aKind==='l3-switch',bSwitch=bKind==='switch'||bKind==='l3-switch';\n      if(!aSwitch||!bSwitch||!carriesVlan(config,link,vlanId))")
text = text.replace("    const aSwitch=deviceById(config,link.a)?.kind==='switch',bSwitch=deviceById(config,link.b)?.kind==='switch';\n    if(!aSwitch||!bSwitch||!carriesVlan(link,vlanId))", "    const aKind=deviceById(config,link.a)?.kind,bKind=deviceById(config,link.b)?.kind; const aSwitch=aKind==='switch'||aKind==='l3-switch',bSwitch=bKind==='switch'||bKind==='l3-switch';\n    if(!aSwitch||!bSwitch||!carriesVlan(config,link,vlanId))")
p.write_text(text)

# Keep Track C UI nested behind the already-lazy authoring workbench.
p = Path('src/BuilderAuthoringPanelContent.tsx')
text = p.read_text()
text = text.replace("import { useEffect, useMemo, useState } from 'react';", "import { lazy, Suspense, useEffect, useMemo, useState } from 'react';")
text = text.replace("import './BuilderAuthoringPanel.css';", "import './BuilderAuthoringPanel.css';\n\nconst BuilderEnterprisePanel = lazy(() => import('./BuilderEnterprisePanel.tsx'));")
text = text.replace("  const [compareAfter, setCompareAfter] = useState('current');", "  const [compareAfter, setCompareAfter] = useState('current');\n  const [enterpriseOpen, setEnterpriseOpen] = useState(false);")
needle = """    </div>\n    <small className=\"builder-authoring-boundary\">UNDO / REDO + BRANCHES STORE CANONICAL BUILDER CONFIGURATION SNAPSHOTS"""
replacement = """    </div>\n    <section className=\"builder-authoring-card\"><div className=\"builder-authoring-card-title\"><span>ENTERPRISE</span><strong>L2 / L3 DEPTH</strong></div><div className=\"builder-authoring-toolbar compact\"><button type=\"button\" onClick={()=>setEnterpriseOpen((open)=>!open)}>{enterpriseOpen?'CLOSE ENTERPRISE':'OPEN ENTERPRISE'}</button></div>{enterpriseOpen&&<Suspense fallback={<small>LOADING ENTERPRISE TOOLS…</small>}><BuilderEnterprisePanel ethernet={snapshot.ethernet} historical={historical} onCommitEthernet={onCommitEthernet} onMessage={onMessage}/></Suspense>}</section>\n    <small className=\"builder-authoring-boundary\">UNDO / REDO + BRANCHES STORE CANONICAL BUILDER CONFIGURATION SNAPSHOTS"""
if needle not in text: raise SystemExit('authoring integration needle not found')
text = text.replace(needle, replacement, 1)
text = text.replace("<small>{link.mode.toUpperCase()} · {link.mode==='access'?`VLAN ${link.accessVlan}`:`${link.allowedVlans?.join(',')}`}</small>", "<small>{link.mode.toUpperCase()} · {link.mode==='access'?`VLAN ${link.accessVlan}`:link.mode==='trunk'?`${link.allowedVlans?.join(',')}`:`VRF ${link.vrfId??'DEFAULT'}`}</small>")
p.write_text(text)

# Register the permanent Track C contract in the normal gate.
p = Path('package.json')
text = p.read_text()
text = text.replace("npm run test:builder-arp-stp-contract && npm run test:builder-link-policy-contract", "npm run test:builder-arp-stp-contract && npm run test:builder-enterprise-contract && npm run test:builder-link-policy-contract")
text = text.replace('    "test:builder-authoring-contract": "node scripts/builder-authoring-contract-check.mjs"', '    "test:builder-authoring-contract": "node scripts/builder-authoring-contract-check.mjs",\n    "test:builder-enterprise-contract": "node scripts/builder-enterprise-contract-check.mjs"')
p.write_text(text)
