import { useMemo, useState } from 'react';
import type { BuilderAddressing } from './builder/addressing.ts';
import { builderIsisState } from './builder/isis.ts';
import type { BuilderGraph } from './builder/model.ts';
import type { BuilderLinkProfiles } from './builder/link-characteristics.ts';
import BuilderProviderPanel from './BuilderProviderPanel.tsx';
import {
  builderOspfTimerFor,
  builderRedistributionHazards,
  cloneBuilderRoutingPolicyConfig,
  upsertBuilderEcmpProfile,
  upsertBuilderIsisRouter,
  upsertBuilderOspfTimer,
  upsertBuilderPbrRule,
  upsertBuilderRedistributionRule,
  upsertBuilderRouteSummary,
  type BuilderEcmpHashMode,
  type BuilderIsisLevel,
  type BuilderRedistributionSource,
  type BuilderRedistributionTarget,
  type BuilderSummaryTarget,
} from './builder/routing-policy.ts';
import { nextHopOptionsForBuilderRouter, setBuilderRoutingPolicyConfig, traceBuilderForwarding, type BuilderRoutingConfig } from './builder/routing.ts';
import './BuilderRoutingPolicyPanel.css';

function labelFor(graph:BuilderGraph,id:string){return graph.nodes.find((node)=>node.id===id)?.label??id.toUpperCase();}

export default function BuilderRoutingPolicyPanel({graph,addressing,routing,linkProfiles,selectedNodeId,selectedLinkId,sourceId,destinationId,historical,onChange,onMessage}:{graph:BuilderGraph;addressing:BuilderAddressing;routing:BuilderRoutingConfig;linkProfiles:BuilderLinkProfiles;selectedNodeId:string;selectedLinkId:string;sourceId:string;destinationId:string;historical:boolean;onChange:(next:BuilderRoutingConfig)=>void;onMessage:(message:string)=>void;}){
  const policy=routing.policy;const selectedRouter=graph.nodes.find((node)=>node.id===selectedNodeId&&node.kind==='router')??null;const selectedLink=graph.links.find((link)=>link.id===selectedLinkId)??null;const nextHops=selectedRouter?nextHopOptionsForBuilderRouter(graph,addressing,selectedRouter.id):[];const hazards=useMemo(()=>builderRedistributionHazards(policy),[policy]);const isisState=useMemo(()=>builderIsisState(graph,addressing,policy.isis),[graph,addressing,policy.isis]);
  const [redistSource,setRedistSource]=useState<BuilderRedistributionSource>('static');const [redistTarget,setRedistTarget]=useState<BuilderRedistributionTarget>('ospf');const [redistPrefix,setRedistPrefix]=useState('0.0.0.0/0');const [pbrSource,setPbrSource]=useState('0.0.0.0/0');const [pbrDestination,setPbrDestination]=useState('0.0.0.0/0');const [summaryPrefix,setSummaryPrefix]=useState('10.0.0.0/8');const [summaryTarget,setSummaryTarget]=useState<BuilderSummaryTarget>('none');const [isisArea,setIsisArea]=useState('49.0001');const [isisLevel,setIsisLevel]=useState<BuilderIsisLevel>('L2');
  const commit=(nextPolicy:typeof policy,detail:string)=>{try{onChange(setBuilderRoutingPolicyConfig(graph,addressing,routing,nextPolicy));onMessage(detail);}catch(error){onMessage(`ROUTING POLICY REJECTED · ${error instanceof Error?error.message:'Invalid policy.'}`);}};
  const selectedEcmp=selectedRouter?policy.ecmpProfiles.find((entry)=>entry.routerId===selectedRouter.id)??{routerId:selectedRouter.id,hashMode:'full' as BuilderEcmpHashMode,maxPaths:8}:null;
  const selectedIsis=selectedRouter?policy.isis.routers.find((entry)=>entry.routerId===selectedRouter.id)??{routerId:selectedRouter.id,enabled:false,areaId:isisArea,level:isisLevel}:null;
  const timerEnds=selectedLink?[selectedLink.a,selectedLink.b].filter((id)=>graph.nodes.find((node)=>node.id===id)?.kind==='router'):[];
  const diagnostic=useMemo(()=>traceBuilderForwarding(graph,addressing,routing,sourceId,destinationId,graph,{protocol:'tcp',sourcePort:42000,destinationPort:443,discriminator:'track-f'}),[graph,addressing,routing,sourceId,destinationId]);
  const remove=(kind:'redist'|'pbr'|'summary',id:string)=>{const next=cloneBuilderRoutingPolicyConfig(policy);if(kind==='redist')next.redistributions=next.redistributions.filter((entry)=>entry.id!==id);if(kind==='pbr')next.pbrRules=next.pbrRules.filter((entry)=>entry.id!==id);if(kind==='summary')next.summaries=next.summaries.filter((entry)=>entry.id!==id);commit(next,`${kind.toUpperCase()} · ${id} removed from canonical routing policy.`);};
  return <><section className="builder-routing-policy" aria-label="Routing and policy depth">
    <div className="builder-routing-policy-title"><div><span>ROUTING POLICY</span><strong>RIB / FIB COMPOSITION</strong></div><small>{historical?'HISTORICAL · READ ONLY':`${hazards.length} REDISTRIBUTION HAZARD${hazards.length===1?'':'S'}`}</small></div>
    <div className="builder-routing-policy-grid">
      <article><header><span>REDISTRIBUTION</span><strong>NATIVE SOURCE → PROTOCOL</strong></header>{selectedRouter?<><div className="policy-inline"><select value={redistSource} onChange={(e)=>setRedistSource(e.currentTarget.value as BuilderRedistributionSource)}>{['connected','static','ospf','bgp','isis'].map((item)=><option key={item} value={item}>{item.toUpperCase()}</option>)}</select><span>→</span><select value={redistTarget} onChange={(e)=>setRedistTarget(e.currentTarget.value as BuilderRedistributionTarget)}>{['ospf','bgp','isis'].map((item)=><option key={item} value={item}>{item.toUpperCase()}</option>)}</select></div><input value={redistPrefix} onChange={(e)=>setRedistPrefix(e.currentTarget.value)} aria-label="Redistribution prefix filter"/><button disabled={historical||redistSource===redistTarget} onClick={()=>{const id=`redist:${selectedRouter.id}:${redistSource}:${redistTarget}:${policy.redistributions.length+1}`;commit(upsertBuilderRedistributionRule(policy,{id,routerId:selectedRouter.id,source:redistSource,target:redistTarget,prefix:redistPrefix,metric:20,routeTag:100+policy.redistributions.length,enabled:true,allowFeedback:false,description:'Track F routing-policy redistribution'}),`REDISTRIBUTION · ${selectedRouter.label} ${redistSource.toUpperCase()} → ${redistTarget.toUpperCase()} added with explicit provenance tag.`);}}>ADD REDISTRIBUTION</button></>:<small>SELECT A ROUTER</small>}<div className="policy-list">{policy.redistributions.map((entry)=><div key={entry.id}><b>{labelFor(graph,entry.routerId)} · {entry.source.toUpperCase()} → {entry.target.toUpperCase()}</b><span>{entry.prefix} · M {entry.metric} · TAG {entry.routeTag}</span><button disabled={historical} onClick={()=>remove('redist',entry.id)}>×</button></div>)}</div>{hazards.map((hazard)=><p key={hazard.id} className="policy-hazard"><b>{hazard.severity}</b>{hazard.detail}</p>)}</article>
      <article><header><span>POLICY-BASED ROUTING</span><strong>FIB STAYS VISIBLE</strong></header>{selectedRouter?<><input value={pbrSource} onChange={(e)=>setPbrSource(e.currentTarget.value)} aria-label="PBR source prefix"/><input value={pbrDestination} onChange={(e)=>setPbrDestination(e.currentTarget.value)} aria-label="PBR destination prefix"/><select id="track-f-next-hop" defaultValue={nextHops[0]?.address??''}>{nextHops.map((hop)=><option key={`${hop.linkId}-${hop.address}`} value={hop.address}>{hop.nodeLabel} · {hop.address}</option>)}</select><button disabled={historical||nextHops.length===0} onClick={()=>{const select=document.getElementById('track-f-next-hop') as HTMLSelectElement|null;const nextHop=select?.value??nextHops[0]?.address;if(!nextHop)return;const id=`pbr:${selectedRouter.id}:${policy.pbrRules.length+1}`;commit(upsertBuilderPbrRule(policy,{id,routerId:selectedRouter.id,order:(policy.pbrRules.filter((entry)=>entry.routerId===selectedRouter.id).at(-1)?.order??0)+10,sourcePrefix:pbrSource,destinationPrefix:pbrDestination,protocol:'ip',sourcePort:null,destinationPort:null,nextHop,enabled:true,description:'Track F PBR'}),`PBR · ${selectedRouter.label} will override the forwarding next hop only after preserving the normal destination FIB decision.`);}}>ADD PBR</button></>:<small>SELECT A ROUTER</small>}<div className="policy-list">{policy.pbrRules.map((entry)=><div key={entry.id}><b>{labelFor(graph,entry.routerId)} · {entry.order} · {entry.protocol.toUpperCase()}</b><span>{entry.sourcePrefix} → {entry.destinationPrefix} · NH {entry.nextHop}</span><button disabled={historical} onClick={()=>remove('pbr',entry.id)}>×</button></div>)}</div><p className={diagnostic.reachable?'policy-ok':'policy-hazard'}><b>CANONICAL TRACE</b>{diagnostic.explanation}</p></article>
      <article><header><span>ECMP</span><strong>PER-FLOW HASH POLICY</strong></header>{selectedEcmp?<><label>HASH MODE<select disabled={historical} value={selectedEcmp.hashMode} onChange={(e)=>commit(upsertBuilderEcmpProfile(policy,{...selectedEcmp,hashMode:e.currentTarget.value as BuilderEcmpHashMode}),`ECMP · ${selectedRouter?.label} hash mode is now ${e.currentTarget.value.toUpperCase()}.`)}><option value="l3">L3 · SRC/DST IP</option><option value="l4">L4 · 5-TUPLE</option><option value="full">FULL · 5-TUPLE + DISCRIMINATOR</option></select></label><label>MAX PATHS<input disabled={historical} type="number" min={1} max={16} value={selectedEcmp.maxPaths} onChange={(e)=>commit(upsertBuilderEcmpProfile(policy,{...selectedEcmp,maxPaths:Number(e.currentTarget.value)}),`ECMP · ${selectedRouter?.label} max paths set to ${e.currentTarget.value}.`)}/></label></>:<small>SELECT A ROUTER</small>}<p>Flow hashing changes only which equal-best FIB next hop is selected. Route preference and metric truth remain unchanged.</p></article>
      <article><header><span>SUMMARIZATION</span><strong>AGGREGATE + DISCARD</strong></header>{selectedRouter?<><input value={summaryPrefix} onChange={(e)=>setSummaryPrefix(e.currentTarget.value)}/><select value={summaryTarget} onChange={(e)=>setSummaryTarget(e.currentTarget.value as BuilderSummaryTarget)}><option value="none">LOCAL DISCARD ONLY</option><option value="ospf">ADVERTISE OSPF</option><option value="bgp">ADVERTISE BGP</option><option value="isis">ADVERTISE IS-IS</option></select><button disabled={historical} onClick={()=>{const id=`summary:${selectedRouter.id}:${policy.summaries.length+1}`;commit(upsertBuilderRouteSummary(policy,{id,routerId:selectedRouter.id,source:'connected',prefix:summaryPrefix,advertiseInto:summaryTarget,metric:10,discard:true,description:'Track F aggregate'}),`SUMMARY · ${selectedRouter.label} installs ${summaryPrefix} as an explicit discard aggregate while more-specific routes keep normal longest-prefix precedence.`);}}>ADD SUMMARY</button></>:<small>SELECT A ROUTER</small>}<div className="policy-list">{policy.summaries.map((entry)=><div key={entry.id}><b>{labelFor(graph,entry.routerId)} · {entry.prefix}</b><span>{entry.source.toUpperCase()} · {entry.advertiseInto.toUpperCase()} · {entry.discard?'DISCARD':'NO DISCARD'}</span><button disabled={historical} onClick={()=>remove('summary',entry.id)}>×</button></div>)}</div></article>
      <article><header><span>OSPF INTERFACE TIMERS</span><strong>PHYSICAL UP ≠ ADJACENCY UP</strong></header>{timerEnds.length===2?<>{timerEnds.map((routerId)=>{const timer=builderOspfTimerFor(policy,routerId,selectedLink!.id);return <div className="policy-timer" key={routerId}><b>{labelFor(graph,routerId)}</b><label>HELLO MS<input disabled={historical} type="number" value={timer.helloIntervalMs} onChange={(e)=>commit(upsertBuilderOspfTimer(policy,{...timer,id:`ospf-timer:${routerId}:${selectedLink!.id}`,helloIntervalMs:Number(e.currentTarget.value)}),`OSPF TIMER · ${labelFor(graph,routerId)} hello interval updated on ${selectedLink!.id}.`)}/></label><label>DEAD MS<input disabled={historical} type="number" value={timer.deadIntervalMs} onChange={(e)=>commit(upsertBuilderOspfTimer(policy,{...timer,id:`ospf-timer:${routerId}:${selectedLink!.id}`,deadIntervalMs:Number(e.currentTarget.value)}),`OSPF TIMER · ${labelFor(graph,routerId)} dead interval updated on ${selectedLink!.id}.`)}/></label></div>;})}</>:<small>SELECT A ROUTER-ROUTER LINK</small>}<p>Timer mismatch removes only the OSPF adjacency/control edge. The physical Builder link remains up for other protocols and data-plane truth.</p></article>
      <article><header><span>IS-IS</span><strong>BOUNDED L1 / L2 IGP</strong></header>{selectedRouter&&selectedIsis?<><label>PROCESS<select disabled={historical} value={selectedIsis.enabled?'on':'off'} onChange={(e)=>commit(upsertBuilderIsisRouter(policy,{...selectedIsis,enabled:e.currentTarget.value==='on'}),`IS-IS · ${selectedRouter.label} ${e.currentTarget.value==='on'?'enabled':'disabled'}.`)}><option value="off">DISABLED</option><option value="on">ENABLED</option></select></label><label>AREA<input disabled={historical} value={selectedIsis.areaId} onChange={(e)=>{setIsisArea(e.currentTarget.value);commit(upsertBuilderIsisRouter(policy,{...selectedIsis,areaId:e.currentTarget.value}),`IS-IS · ${selectedRouter.label} area set to ${e.currentTarget.value}.`);}}/></label><label>LEVEL<select disabled={historical} value={selectedIsis.level} onChange={(e)=>{const level=e.currentTarget.value as BuilderIsisLevel;setIsisLevel(level);commit(upsertBuilderIsisRouter(policy,{...selectedIsis,level}),`IS-IS · ${selectedRouter.label} level ${level}.`);}}><option value="L1">L1</option><option value="L2">L2</option><option value="L1L2">L1/L2</option></select></label></>:<small>SELECT A ROUTER</small>}<div className="policy-facts"><span><b>{isisState.enabledRouterIds.length}</b>ROUTERS</span><span><b>{isisState.adjacencies.filter((entry)=>entry.state==='UP').length}</b>ADJ UP</span><span><b>{isisState.l1Areas.length}</b>L1 AREAS</span><span><b>{isisState.l2RouterIds.length}</b>L2 ROUTERS</span></div><p>IS-IS uses the same routed graph and link costs. L1 stays area-scoped; L2 provides inter-area reachability. It is another control-plane projection, not another topology.</p></article>
    </div>
    <small className="builder-routing-policy-boundary">REDISTRIBUTION CONSUMES ONLY NATIVE PROTOCOL ROUTES BY DEFAULT · REDISTRIBUTED PROVENANCE/TAGS REMAIN EXPLICIT · PBR PRESERVES THE DESTINATION FIB DECISION · SUMMARY DISCARD IS AN INTENTIONAL BLACK-HOLE BOUNDARY · ALL STATE IS SIMULATED CANONICAL BUILDER CONFIGURATION.</small>
  </section><BuilderProviderPanel graph={graph} addressing={addressing} routing={routing} linkProfiles={linkProfiles} selectedNodeId={selectedNodeId} historical={historical} onChange={onChange} onMessage={onMessage}/></>;
}
