import { useEffect, useMemo, useState } from 'react';
import type { BuilderAddressing } from './builder/addressing.ts';
import type { BuilderGraph } from './builder/model.ts';
import type { BuilderRoutingConfig } from './builder/routing.ts';
import {
  builderBgpAsnForRouter,
  builderBgpBestRoutesForRouter,
  builderBgpState,
  deleteBuilderBgpOrigin,
  deleteBuilderBgpPolicy,
  deleteBuilderBgpSession,
  projectBuilderBgpToAsGraph,
  setBuilderBgpRouterAsn,
  setBuilderBgpRouterEnabled,
  updateBuilderBgpSession,
  upsertBuilderBgpOrigin,
  upsertBuilderBgpPolicy,
  upsertBuilderBgpSession,
  type BuilderBgpPolicyAction,
  type BuilderBgpPolicyDirection,
} from './builder/bgp.ts';

function labelFor(graph:BuilderGraph,id:string):string{return graph.nodes.find((node)=>node.id===id)?.label??id.toUpperCase();}

export function BuilderBgpPanel({graph,addressing,routing,selectedNodeId,selectedLinkId,destinationPrefix,onChange,onMessage}:{graph:BuilderGraph;addressing:BuilderAddressing;routing:BuilderRoutingConfig;selectedNodeId:string;selectedLinkId:string;destinationPrefix:string;onChange:(next:BuilderRoutingConfig)=>void;onMessage:(message:string)=>void;}){
  const selectedNode=graph.nodes.find((node)=>node.id===selectedNodeId)??null;const selectedLink=graph.links.find((link)=>link.id===selectedLinkId)??null;const bgp=routing.bgp;const state=useMemo(()=>builderBgpState(graph,addressing,bgp),[graph,addressing,bgp]);const selectedAsn=selectedNode?.kind==='router'?builderBgpAsnForRouter(graph,bgp,selectedNode.id):null;const selectedEnabled=Boolean(selectedNode?.kind==='router'&&bgp.enabledRouterIds.includes(selectedNode.id));const selectedSession=selectedLink?bgp.sessions.find((entry)=>entry.linkId===selectedLink.id)??null:null;const sessionState=selectedSession?state.sessions.find((entry)=>entry.id===selectedSession.id)??null:null;const selectedRoutes=selectedNode?.kind==='router'?state.routes.filter((route)=>route.routerId===selectedNode.id):[];const bestRoutes=selectedNode?.kind==='router'?builderBgpBestRoutesForRouter(state,selectedNode.id):[];const selectedOrigins=selectedNode?.kind==='router'?bgp.origins.filter((origin)=>origin.routerId===selectedNode.id):[];const selectedPolicies=selectedNode?.kind==='router'?bgp.policies.filter((rule)=>rule.routerId===selectedNode.id):[];
  const [asnDraft,setAsnDraft]=useState(selectedAsn??64496);const [originPrefix,setOriginPrefix]=useState(destinationPrefix);const [med,setMed]=useState(0);const [community,setCommunity]=useState('64496:100');const [policyDirection,setPolicyDirection]=useState<BuilderBgpPolicyDirection>('import');const [policyAction,setPolicyAction]=useState<BuilderBgpPolicyAction>('permit');const [localPref,setLocalPref]=useState('200');const [policyMed,setPolicyMed]=useState('');const [policyCommunity,setPolicyCommunity]=useState('');const [allowLeak,setAllowLeak]=useState(false);
  useEffect(()=>{if(selectedAsn)setAsnDraft(selectedAsn);},[selectedAsn]);useEffect(()=>setOriginPrefix(destinationPrefix),[destinationPrefix]);
  const commitBgp=(nextBgp:BuilderRoutingConfig['bgp'],detail:string)=>{onChange({...routing,bgp:nextBgp});onMessage(detail);};
  const setAsn=()=>{if(!selectedNode||selectedNode.kind!=='router')return;try{commitBgp(setBuilderBgpRouterAsn(graph,bgp,selectedNode.id,asnDraft),`BGP ASN · ${selectedNode.label} is now AS${asnDraft}. Session type is derived again from peer ASNs.`);}catch(error){onMessage(`BGP ASN REJECTED · ${error instanceof Error?error.message:'Invalid ASN.'}`);}};
  const toggleRouter=()=>{if(!selectedNode||selectedNode.kind!=='router')return;commitBgp(setBuilderBgpRouterEnabled(graph,bgp,selectedNode.id,!selectedEnabled),`BGP · ${selectedNode.label} ${selectedEnabled?'disabled':'enabled'} in AS${selectedAsn}.`);};
  const createSession=()=>{if(!selectedLink)return;try{const next=upsertBuilderBgpSession(graph,bgp,selectedLink.id,'peer');commitBgp(next,`BGP SESSION · ${labelFor(graph,selectedLink.a)} ↔ ${labelFor(graph,selectedLink.b)} authored as ${builderBgpAsnForRouter(graph,next,selectedLink.a)===builderBgpAsnForRouter(graph,next,selectedLink.b)?'iBGP':'eBGP'}.`);}catch(error){onMessage(`BGP SESSION REJECTED · ${error instanceof Error?error.message:'Invalid session.'}`);}};
  const patchSession=(patch:Parameters<typeof updateBuilderBgpSession>[3],detail:string)=>{if(!selectedSession)return;try{commitBgp(updateBuilderBgpSession(graph,bgp,selectedSession.id,patch),detail);}catch(error){onMessage(`BGP SESSION REJECTED · ${error instanceof Error?error.message:'Invalid session update.'}`);}};
  const originate=()=>{if(!selectedNode||selectedNode.kind!=='router')return;try{const next=upsertBuilderBgpOrigin(graph,bgp,{routerId:selectedNode.id,prefix:originPrefix,med,communities:community.trim()?[community.trim()]:[],description:'Builder-originated BGP prefix'});commitBgp(next,`BGP ORIGIN · ${selectedNode.label} AS${selectedAsn} now originates ${originPrefix}. A second ASN may originate the same prefix to demonstrate hijack/multi-origin truth.`);}catch(error){onMessage(`BGP ORIGIN REJECTED · ${error instanceof Error?error.message:'Invalid BGP origin.'}`);}};
  const addPolicy=()=>{if(!selectedNode||selectedNode.kind!=='router')return;try{const order=selectedPolicies.length?Math.max(...selectedPolicies.map((rule)=>rule.order))+10:10;const next=upsertBuilderBgpPolicy(graph,bgp,{routerId:selectedNode.id,direction:policyDirection,sessionId:selectedSession?.id??null,order,action:policyAction,prefix:originPrefix,setLocalPref:localPref.trim()===''?null:Number(localPref),setMed:policyMed.trim()===''?null:Number(policyMed),addCommunity:policyCommunity.trim()||null,allowRelationshipLeak:allowLeak,description:`${policyDirection.toUpperCase()} ${policyAction.toUpperCase()} ${originPrefix}`});commitBgp(next,`BGP POLICY · ${selectedNode.label} ${policyDirection.toUpperCase()} ${policyAction.toUpperCase()} ${originPrefix}${allowLeak?' · RELATIONSHIP LEAK OVERRIDE':''}.`);}catch(error){onMessage(`BGP POLICY REJECTED · ${error instanceof Error?error.message:'Invalid BGP policy.'}`);}};
  const projection=useMemo(()=>projectBuilderBgpToAsGraph(graph,bgp,state,selectedNode?.kind==='router'?selectedNode.id:undefined,undefined,originPrefix),[graph,bgp,state,selectedNode,originPrefix]);
  return <section className="builder-bgp-section"><div className="control-title"><span>BGP · PATH VECTOR</span><strong>{state.sessions.filter((entry)=>entry.state==='ESTABLISHED').length} EST · {state.bestRoutes.length} BEST</strong></div>{selectedNode?.kind==='router'?<><div className="builder-ospf-facts"><div><span>SELECTED ASN</span><strong>AS{selectedAsn}</strong></div><div><span>PROCESS</span><strong>{selectedEnabled?'ENABLED':'DISABLED'}</strong></div></div><div className="builder-static-form"><label>DOCUMENTATION ASN<input type="number" min={64496} max={65551} value={asnDraft} onChange={(event)=>setAsnDraft(Math.round(Number(event.currentTarget.value)||64496))}/></label><button type="button" onClick={setAsn}>SET ASN</button><button type="button" onClick={toggleRouter}>{selectedEnabled?'DISABLE BGP':'ENABLE BGP'}</button></div></>:<small className="builder-routing-note">Select a router to author BGP.</small>}
  <div className="control-title"><span>SELECTED PEERING LINK</span><strong>{selectedLink?selectedLink.id.toUpperCase():'NONE'}</strong></div>{selectedLink&&graph.nodes.find((node)=>node.id===selectedLink.a)?.kind==='router'&&graph.nodes.find((node)=>node.id===selectedLink.b)?.kind==='router'?selectedSession?<><div className="builder-ospf-facts"><div><span>SESSION</span><strong>{sessionState?.mode.toUpperCase()} · {sessionState?.state}</strong></div><div><span>RELATIONSHIP</span><strong>{selectedSession.relationship.toUpperCase()}</strong></div></div><small className="builder-routing-note">AS{sessionState?.aAsn} {labelFor(graph,selectedSession.aRouterId)} ↔ AS{sessionState?.bAsn} {labelFor(graph,selectedSession.bRouterId)} · {sessionState?.reason}</small><div className="button-row"><button type="button" onClick={()=>patchSession({enabled:!selectedSession.enabled},`BGP SESSION · ${selectedSession.enabled?'administratively down':'enabled'}.`)}>{selectedSession.enabled?'DISABLE SESSION':'ENABLE SESSION'}</button>{sessionState?.mode==='ibgp'?<button type="button" onClick={()=>patchSession({nextHopSelf:!selectedSession.nextHopSelf},`iBGP NEXT-HOP-SELF · ${!selectedSession.nextHopSelf?'enabled':'disabled'}.`)}>NEXT-HOP-SELF {selectedSession.nextHopSelf?'ON':'OFF'}</button>:<><button type="button" onClick={()=>patchSession({relationship:'peer',customerRouterId:null},'eBGP relationship set to PEER.')}>PEER</button><button type="button" onClick={()=>patchSession({relationship:'customer-provider',customerRouterId:selectedSession.aRouterId},`${labelFor(graph,selectedSession.aRouterId)} is CUSTOMER.`)}>A CUSTOMER</button><button type="button" onClick={()=>patchSession({relationship:'customer-provider',customerRouterId:selectedSession.bRouterId},`${labelFor(graph,selectedSession.bRouterId)} is CUSTOMER.`)}>B CUSTOMER</button><button type="button" onClick={()=>patchSession({allowRelationshipLeak:!selectedSession.allowRelationshipLeak},`RELATIONSHIP LEAK OVERRIDE ${!selectedSession.allowRelationshipLeak?'ENABLED':'DISABLED'}.`)}>LEAK {selectedSession.allowRelationshipLeak?'ON':'OFF'}</button></>}</div><button type="button" onClick={()=>commitBgp(deleteBuilderBgpSession(graph,bgp,selectedSession.id),'BGP session removed; derived routes withdrawn.')}>DELETE SESSION</button></>:<button type="button" onClick={createSession}>AUTHOR BGP SESSION</button>:<small className="builder-routing-note">Select a direct router-router link to author eBGP/iBGP.</small>}
  {selectedNode?.kind==='router'&&<><div className="control-title"><span>NETWORK ORIGINATION</span><strong>{selectedOrigins.length} PREFIXES</strong></div><div className="builder-static-form"><label>PREFIX<input value={originPrefix} onChange={(event)=>setOriginPrefix(event.currentTarget.value)}/></label><button type="button" onClick={()=>setOriginPrefix(destinationPrefix)}>USE DEST PREFIX</button><label>MED<input type="number" min={0} value={med} onChange={(event)=>setMed(Math.max(0,Math.round(Number(event.currentTarget.value)||0)))}/></label><label>COMMUNITY<input value={community} onChange={(event)=>setCommunity(event.currentTarget.value)}/></label><button type="button" onClick={originate}>ORIGINATE / UPDATE</button></div><div className="builder-interface-list">{selectedOrigins.length===0?<small>NO BGP NETWORK STATEMENTS</small>:selectedOrigins.map((origin)=><div key={origin.id}><span>{origin.prefix}</span><strong>MED {origin.med} · {origin.communities.join(' ')||'NO COMMUNITY'}</strong><small>{origin.description}</small><button type="button" onClick={()=>commitBgp(deleteBuilderBgpOrigin(graph,bgp,origin.id),`BGP WITHDRAW · ${origin.prefix} removed; control plane recomputed.`)}>×</button></div>)}</div>
  <div className="control-title"><span>IMPORT / EXPORT POLICY</span><strong>{selectedPolicies.length} RULES</strong></div><div className="builder-static-form"><label>DIRECTION<select value={policyDirection} onChange={(event)=>setPolicyDirection(event.currentTarget.value as BuilderBgpPolicyDirection)}><option value="import">IMPORT</option><option value="export">EXPORT</option></select></label><label>ACTION<select value={policyAction} onChange={(event)=>setPolicyAction(event.currentTarget.value as BuilderBgpPolicyAction)}><option value="permit">PERMIT</option><option value="deny">DENY</option></select></label><label>LOCAL_PREF<input value={localPref} onChange={(event)=>setLocalPref(event.currentTarget.value)} placeholder="UNCHANGED"/></label><label>MED<input value={policyMed} onChange={(event)=>setPolicyMed(event.currentTarget.value)} placeholder="UNCHANGED"/></label><label>ADD COMMUNITY<input value={policyCommunity} onChange={(event)=>setPolicyCommunity(event.currentTarget.value)} placeholder="NONE"/></label><label><input type="checkbox" checked={allowLeak} onChange={(event)=>setAllowLeak(event.currentTarget.checked)}/>ALLOW RELATIONSHIP LEAK</label><button type="button" onClick={addPolicy}>ADD POLICY FOR PREFIX</button></div><div className="builder-interface-list">{selectedPolicies.length===0?<small>NO EXPLICIT BGP POLICY · DEFAULT PERMIT + SHARED VALLEY-FREE RELATIONSHIP EXPORT</small>:selectedPolicies.map((rule)=><div key={rule.id}><span>{rule.order} · {rule.direction.toUpperCase()} · {rule.action.toUpperCase()}</span><strong>{rule.prefix}</strong><small>{rule.sessionId??'ANY SESSION'} · LP {rule.setLocalPref??'KEEP'} · MED {rule.setMed??'KEEP'} · COMMUNITY {rule.addCommunity??'KEEP'}{rule.allowRelationshipLeak?' · LEAK OVERRIDE':''}</small><button type="button" onClick={()=>commitBgp(deleteBuilderBgpPolicy(graph,bgp,rule.id),'BGP policy removed; Adj-RIB state recomputed.')}>×</button></div>)}</div>
  <div className="control-title"><span>BGP RIB</span><strong>{bestRoutes.length} BEST · {selectedRoutes.length} CANDIDATES</strong></div><div className="builder-route-table">{selectedRoutes.length===0?<small>NO BGP ROUTES</small>:selectedRoutes.slice(0,24).map((route)=><div key={route.id} className={`${route.best?'':'inactive'} ${route.policyAnomaly?'denied':''}`}><span>{route.best?'BEST':'ALT'}</span><strong>{route.prefix}</strong><small>LP {route.localPref} · AS_PATH {route.asPath.length?route.asPath.join(' '):'LOCAL'} · MED {route.med} · NEXT_HOP {route.nextHopAddress} · {route.learnedVia.toUpperCase()} · {route.communities.join(' ')||'NO COMM'}{route.policyAnomaly?' · LEAK':''}</small></div>)}</div></>}
  <div className="builder-ospf-facts"><div><span>ANOMALIES</span><strong>{state.multiOriginPrefixes.length} MULTI-ORIGIN · {state.leakedRouteIds.length} LEAKED</strong></div><div><span>AS PROJECTION</span><strong>{projection.graph.nodes.length} AS · {projection.graph.relationships.length} REL</strong></div></div>{state.multiOriginPrefixes.length>0&&<small className="builder-routing-note">MULTI-ORIGIN / HIJACK TEACHING STATE · {state.multiOriginPrefixes.join(', ')} is originated by more than one ASN. Best-path policy decides which advertisement wins.</small>}<small className="builder-routing-note">BEST PATH · HIGHEST LOCAL_PREF → SHORTEST AS_PATH → LOWEST MED → LOCAL/eBGP/iBGP → STABLE ROUTER ID. eBGP AD 20 · iBGP AD 200 are HOPSCOTCH teaching defaults, not BGP wire attributes. Relationship export policy is shared with Lab 05.</small></section>;
}
