import { useMemo, useState } from 'react';
import { interfacesForBuilderNode, type BuilderAddressing } from './builder/addressing.ts';
import type { BuilderLinkProfiles } from './builder/link-characteristics.ts';
import type { BuilderGraph } from './builder/model.ts';
import { builderEvpnRoutes, builderMplsForwardingTable, builderProviderFacts, builderTunnelPacketProjection, builderVxlanForwarding } from './builder/provider.ts';
import { cloneBuilderProviderConfig, createDefaultBuilderProviderConfig, upsertBuilderEvpnBinding, upsertBuilderMplsLsp, upsertBuilderTunnel, upsertBuilderVni, upsertBuilderVtep, type BuilderTunnelKind, type BuilderTunnelSecurityState } from './builder/provider-config.ts';
import { setBuilderProviderConfig, type BuilderRoutingConfig } from './builder/routing.ts';
import './BuilderProviderPanel.css';

function labelFor(graph:BuilderGraph,id:string){return graph.nodes.find((node)=>node.id===id)?.label??id.toUpperCase();}
function firstAddress(addressing:BuilderAddressing,id:string){return interfacesForBuilderNode(addressing,id)[0]?.address??'';}

function BuilderProviderPanelContent({graph,addressing,routing,linkProfiles,selectedNodeId,historical,onChange,onMessage}:{graph:BuilderGraph;addressing:BuilderAddressing;routing:BuilderRoutingConfig;linkProfiles:BuilderLinkProfiles;selectedNodeId:string;historical:boolean;onChange:(next:BuilderRoutingConfig)=>void;onMessage:(message:string)=>void;}){
  const provider=routing.provider??createDefaultBuilderProviderConfig(),routers=graph.nodes.filter((node)=>node.kind==='router'),selectedRouter=routers.find((node)=>node.id===selectedNodeId)??null,otherRouters=selectedRouter?routers.filter((node)=>node.id!==selectedRouter.id):routers;
  const [remoteRouterId,setRemoteRouterId]=useState(otherRouters[0]?.id??'');const [tunnelKind,setTunnelKind]=useState<BuilderTunnelKind>('gre');const [securityState,setSecurityState]=useState<BuilderTunnelSecurityState>('ready');const [overlayPrefix,setOverlayPrefix]=useState('172.31.255.0/30');const [localTunnelAddress,setLocalTunnelAddress]=useState('172.31.255.1');const [remoteTunnelAddress,setRemoteTunnelAddress]=useState('172.31.255.2');const [fecPrefix,setFecPrefix]=useState('10.0.0.0/8');const [vniValue,setVniValue]=useState(10100);const [routeTarget,setRouteTarget]=useState('65000:10100');const [mac,setMac]=useState('02:00:00:00:10:01');const [bindingIp,setBindingIp]=useState('10.10.0.10');
  const facts=useMemo(()=>builderProviderFacts(graph,addressing,routing,linkProfiles),[graph,addressing,routing,linkProfiles]);const selectedEvpn=useMemo(()=>selectedRouter?builderEvpnRoutes(graph,addressing,routing,selectedRouter.id):[],[graph,addressing,routing,selectedRouter]);const selectedMpls=useMemo(()=>selectedRouter?builderMplsForwardingTable(graph,addressing,routing,selectedRouter.id):[],[graph,addressing,routing,selectedRouter]);
  const commit=(nextProvider:typeof provider,detail:string)=>{try{onChange(setBuilderProviderConfig(graph,addressing,routing,nextProvider));onMessage(detail);}catch(error){onMessage(`PROVIDER MODEL REJECTED · ${error instanceof Error?error.message:'Invalid provider configuration.'}`);}};
  const remove=(kind:'tunnel'|'lsp'|'vni'|'binding',id:string|number)=>{const next=cloneBuilderProviderConfig(provider);if(kind==='tunnel')next.tunnels=next.tunnels.filter((entry)=>entry.id!==id);if(kind==='lsp')next.mpls.lsps=next.mpls.lsps.filter((entry)=>entry.id!==id);if(kind==='vni'){next.vxlan.vnis=next.vxlan.vnis.filter((entry)=>entry.vni!==id);next.vxlan.bindings=next.vxlan.bindings.filter((entry)=>entry.vni!==id);}if(kind==='binding')next.vxlan.bindings=next.vxlan.bindings.filter((entry)=>entry.id!==id);commit(next,`PROVIDER MODEL · ${kind.toUpperCase()} ${id} removed.`);};
  const addTunnel=()=>{if(!selectedRouter||!remoteRouterId)return;const encrypted=tunnelKind==='ipsec'||tunnelKind==='wireguard',id=`tunnel:${tunnelKind}:${selectedRouter.id}:${remoteRouterId}`;commit(upsertBuilderTunnel(provider,{id,kind:tunnelKind,sourceRouterId:selectedRouter.id,destinationRouterId:remoteRouterId,overlayPrefix,localTunnelAddress,remoteTunnelAddress,enabled:true,securityState:encrypted?securityState:'none',description:'Provider overlay tunnel'}),`TUNNEL · ${tunnelKind.toUpperCase()} keeps inner overlay addresses separate from canonical underlay forwarding.`);};
  const toggleMpls=()=>{if(!selectedRouter)return;const next=cloneBuilderProviderConfig(provider),ids=new Set(next.mpls.enabledRouterIds);if(ids.has(selectedRouter.id))ids.delete(selectedRouter.id);else ids.add(selectedRouter.id);next.mpls.enabledRouterIds=[...ids].sort();next.mpls.lsps=next.mpls.lsps.filter((entry)=>ids.has(entry.ingressRouterId)&&ids.has(entry.egressRouterId));commit(next,`MPLS · ${selectedRouter.label} ${ids.has(selectedRouter.id)?'enabled':'disabled'}.`);};
  const addLsp=()=>{if(!selectedRouter||!remoteRouterId)return;const next=cloneBuilderProviderConfig(provider);for(const id of [selectedRouter.id,remoteRouterId])if(!next.mpls.enabledRouterIds.includes(id))next.mpls.enabledRouterIds.push(id);next.mpls.enabledRouterIds.sort();commit(upsertBuilderMplsLsp(next,{id:`lsp:${selectedRouter.id}:${remoteRouterId}:${next.mpls.lsps.length+1}`,ingressRouterId:selectedRouter.id,egressRouterId:remoteRouterId,fecPrefix,enabled:true,description:'Provider label-switched path'}),`MPLS · LSP ${selectedRouter.label} → ${labelFor(graph,remoteRouterId)} derives push/swap/pop from the canonical underlay path.`);};
  const addVtep=()=>{if(!selectedRouter)return;const sourceAddress=firstAddress(addressing,selectedRouter.id);if(!sourceAddress){onMessage('VTEP REJECTED · selected router has no routed IPv4 interface.');return;}commit(upsertBuilderVtep(provider,{routerId:selectedRouter.id,sourceAddress,enabled:true}),`VXLAN · ${selectedRouter.label} VTEP source is ${sourceAddress}.`);};
  const addVni=()=>{const members=provider.vxlan.vteps.filter((entry)=>entry.enabled).map((entry)=>entry.routerId);if(members.length<2){onMessage('VNI REJECTED · configure at least two VTEPs first.');return;}commit(upsertBuilderVni(provider,{id:`vni:${vniValue}`,vni:vniValue,memberVtepRouterIds:members,routeTarget,description:'Provider VXLAN segment'}),`VXLAN · VNI ${vniValue} uses ${members.length} VTEPs; overlay state remains dependent on underlay reachability.`);};
  const addBinding=()=>{if(!selectedRouter)return;const network=provider.vxlan.vnis.find((entry)=>entry.memberVtepRouterIds.includes(selectedRouter.id));if(!network){onMessage('EVPN BINDING REJECTED · selected VTEP is not a member of any VNI.');return;}commit(upsertBuilderEvpnBinding(provider,{id:`evpn:${network.vni}:${selectedRouter.id}:${mac.replaceAll(':','')}`,vni:network.vni,vtepRouterId:selectedRouter.id,mac,ip:bindingIp||null,attachment:`${selectedRouter.label} LOCAL L2`,description:'Provider MAC/IP binding'}),`EVPN · local MAC/IP binding advertised from ${selectedRouter.label} as a bounded Type-2 route.`);};
  const sampleTunnel=provider.tunnels[0];const packet=sampleTunnel?builderTunnelPacketProjection(graph,addressing,routing,linkProfiles,sampleTunnel,{source:sampleTunnel.localTunnelAddress,destination:sampleTunnel.remoteTunnelAddress,bytes:1400}):null;const sampleBinding=provider.vxlan.bindings[0];const samplePeer=sampleBinding?provider.vxlan.bindings.find((entry)=>entry.vni===sampleBinding.vni&&entry.vtepRouterId!==sampleBinding.vtepRouterId):null;const vxlanForward=sampleBinding&&samplePeer?builderVxlanForwarding(graph,addressing,routing,sampleBinding,samplePeer.mac):null;
  return <section className="builder-provider" aria-label="Service provider and overlay networking">
    <div className="builder-provider-title"><div><span>SERVICE PROVIDER / OVERLAY</span><strong>UNDERLAY TRUTH → ENCAPSULATION → OVERLAY</strong></div><small>{historical?'HISTORICAL · READ ONLY':`${facts.tunnels.filter((entry)=>entry.state==='UP').length} TUNNELS UP · ${facts.lsps.filter((entry)=>entry.state==='UP').length} LSPS UP`}</small></div>
    <div className="builder-provider-grid">
      <article><header><span>TUNNELS</span><strong>INNER ≠ OUTER</strong></header>{selectedRouter?<><div className="provider-inline"><select value={tunnelKind} onChange={(e)=>setTunnelKind(e.currentTarget.value as BuilderTunnelKind)}><option value="gre">GRE</option><option value="ipip">IP-IN-IP</option><option value="ipsec">IPSEC-STYLE</option><option value="wireguard">WIREGUARD-STYLE</option></select><select value={remoteRouterId} onChange={(e)=>setRemoteRouterId(e.currentTarget.value)}>{otherRouters.map((router)=><option key={router.id} value={router.id}>{router.label}</option>)}</select></div><input value={overlayPrefix} onChange={(e)=>setOverlayPrefix(e.currentTarget.value)} aria-label="Tunnel overlay prefix"/><div className="provider-inline"><input value={localTunnelAddress} onChange={(e)=>setLocalTunnelAddress(e.currentTarget.value)} aria-label="Local tunnel address"/><input value={remoteTunnelAddress} onChange={(e)=>setRemoteTunnelAddress(e.currentTarget.value)} aria-label="Remote tunnel address"/></div>{(tunnelKind==='ipsec'||tunnelKind==='wireguard')&&<select value={securityState} onChange={(e)=>setSecurityState(e.currentTarget.value as BuilderTunnelSecurityState)}><option value="ready">AUTH / HANDSHAKE READY</option><option value="auth-failed">AUTH FAILED</option><option value="key-missing">KEY MISSING</option><option value="handshake-down">HANDSHAKE DOWN</option></select>}<button disabled={historical||!remoteRouterId} onClick={addTunnel}>ADD / REPLACE TUNNEL</button></>:<small>SELECT A ROUTER</small>}<div className="provider-list">{facts.tunnels.map((state)=><div key={state.tunnelId} className={state.state==='UP'?'up':'down'}><b>{state.kind.toUpperCase()} · {state.tunnelId}</b><span>{state.state} · UNDERLAY {state.underlayReachable?'UP':'DOWN'} · OVERLAY {state.overlayReachable?'UP':'DOWN'} · MTU {state.effectiveOverlayMtuBytes??'—'}</span><small>{state.reason}</small><button disabled={historical} onClick={()=>remove('tunnel',state.tunnelId)}>×</button></div>)}</div>{packet&&<p><b>ENCAPSULATION SAMPLE</b>{packet.state} · INNER {packet.inner.bytes} B → OUTER {packet.outer.bytes} B · {packet.reason}</p>}</article>
      <article><header><span>ENCRYPTED TUNNELS</span><strong>SEMANTICS, NOT CRYPTOGRAPHY</strong></header><p>IPsec-style and WireGuard-style state models authentication/handshake readiness, encapsulation overhead, underlay reachability, and effective MTU. HOPSCOTCH stores no secret key material and does not claim production cryptographic behavior.</p><div className="provider-facts"><span><b>{provider.tunnels.filter((entry)=>entry.kind==='ipsec'||entry.kind==='wireguard').length}</b>ENCRYPTED</span><span><b>{provider.tunnels.filter((entry)=>(entry.kind==='ipsec'||entry.kind==='wireguard')&&entry.securityState!=='ready').length}</b>SECURITY DOWN</span></div></article>
      <article><header><span>MPLS</span><strong>LABEL FORWARDING</strong></header>{selectedRouter?<><div className="provider-inline"><button disabled={historical} onClick={toggleMpls}>{provider.mpls.enabledRouterIds.includes(selectedRouter.id)?'DISABLE MPLS':'ENABLE MPLS'} · {selectedRouter.label}</button><select value={remoteRouterId} onChange={(e)=>setRemoteRouterId(e.currentTarget.value)}>{otherRouters.map((router)=><option key={router.id} value={router.id}>{router.label}</option>)}</select></div><input value={fecPrefix} onChange={(e)=>setFecPrefix(e.currentTarget.value)} aria-label="MPLS FEC prefix"/><button disabled={historical||!remoteRouterId} onClick={addLsp}>ADD LSP</button></>:<small>SELECT A ROUTER</small>}<div className="provider-list">{facts.lsps.map((state)=><div key={state.lspId} className={state.state==='UP'?'up':'down'}><b>{state.lspId} · {state.state}</b><span>{state.routerPath.map((id)=>labelFor(graph,id)).join(' → ')}</span><small>{state.operations.map((op)=>`${labelFor(graph,op.routerId)} ${op.operation}${op.outLabel?` ${op.outLabel}`:''}`).join(' · ')||state.reason}</small><button disabled={historical} onClick={()=>remove('lsp',state.lspId)}>×</button></div>)}</div>{selectedRouter&&<div className="provider-table">{selectedMpls.map((row)=><div key={`${row.lspId}-${row.operation}`}><span>{row.operation}</span><b>{row.inLabel??'IP'} → {row.outLabel??'IP'}</b><small>{row.fecPrefix} · {row.outgoingLinkId??'LOCAL POP'}</small></div>)}</div>}</article>
      <article><header><span>VXLAN</span><strong>VNI / VTEP OVERLAY</strong></header>{selectedRouter&&<button disabled={historical} onClick={addVtep}>ADD / REPLACE VTEP · {selectedRouter.label}</button>}<div className="provider-list">{provider.vxlan.vteps.map((entry)=><div key={entry.routerId}><b>{labelFor(graph,entry.routerId)} · {entry.sourceAddress}</b><span>{entry.enabled?'VTEP ENABLED':'VTEP DISABLED'}</span></div>)}</div><div className="provider-inline"><input type="number" min={1} max={16777215} value={vniValue} onChange={(e)=>setVniValue(Number(e.currentTarget.value))}/><input value={routeTarget} onChange={(e)=>setRouteTarget(e.currentTarget.value)} aria-label="EVPN route target"/></div><button disabled={historical} onClick={addVni}>ADD VNI USING ACTIVE VTEPS</button><div className="provider-list">{facts.vnis.map((state)=><div key={state.vni} className={state.state==='UP'?'up':'down'}><b>VNI {state.vni} · {state.state}</b><span>{state.activeVtepRouterIds.map((id)=>labelFor(graph,id)).join(' · ')}</span><small>{state.reason}</small><button disabled={historical} onClick={()=>remove('vni',state.vni)}>×</button></div>)}</div>{vxlanForward&&<p><b>FORWARDING SAMPLE</b>{vxlanForward.mode} · {vxlanForward.reason}</p>}</article>
      <article><header><span>EVPN</span><strong>MAC/IP CONTROL PLANE</strong></header><label>CONTROL PLANE<select disabled={historical} value={provider.vxlan.evpnEnabled?'on':'off'} onChange={(e)=>{const next=cloneBuilderProviderConfig(provider);next.vxlan.evpnEnabled=e.currentTarget.value==='on';commit(next,`EVPN · BGP MAC/IP learning ${next.vxlan.evpnEnabled?'enabled':'disabled'}.`);}}><option value="off">DISABLED</option><option value="on">BGP EVPN ENABLED</option></select></label>{selectedRouter&&<><div className="provider-inline"><input value={mac} onChange={(e)=>setMac(e.currentTarget.value)} aria-label="EVPN MAC"/><input value={bindingIp} onChange={(e)=>setBindingIp(e.currentTarget.value)} aria-label="EVPN IP"/></div><button disabled={historical} onClick={addBinding}>ADD LOCAL MAC/IP BINDING</button></>}<div className="provider-list">{provider.vxlan.bindings.map((entry)=><div key={entry.id}><b>VNI {entry.vni} · {entry.mac}</b><span>{entry.ip??'MAC ONLY'} · {labelFor(graph,entry.vtepRouterId)}</span><button disabled={historical} onClick={()=>remove('binding',entry.id)}>×</button></div>)}</div>{selectedRouter&&<div className="provider-table">{selectedEvpn.map((route)=><div key={route.id}><span>{route.learned}</span><b>{route.mac}{route.ip?` · ${route.ip}`:''}</b><small>VNI {route.vni} · NH {route.nextHop} · RT {route.routeTarget}</small></div>)}</div>}<p>Remote Type-2 learning requires both an established BGP-session path and canonical underlay reachability. VXLAN forwarding never treats overlay learning as proof that the underlay works.</p></article>
    </div>
    <small className="builder-provider-boundary">UNDERLAY ROUTING / FAILURES REMAIN CANONICAL BUILDER RIB/FIB TRUTH · TUNNELS ADD EXPLICIT OUTER HEADERS WITHOUT REWRITING INNER ADDRESSES · MPLS OPERATIONS ARE DERIVED FROM THE CANONICAL UNDERLAY PATH · VXLAN/EVPN KEEP VTEP REACHABILITY AND MAC/IP LEARNING SEPARATE · ENCRYPTED-TUNNEL STATE IS A TEACHING SEMANTIC, NOT PRODUCTION CRYPTOGRAPHY.</small>
  </section>;
}

export default function BuilderProviderPanel(props:Parameters<typeof BuilderProviderPanelContent>[0]){
  const [open,setOpen]=useState(false);
  const provider=props.routing.provider??createDefaultBuilderProviderConfig();
  if(!open)return <section className="builder-provider builder-provider-shell" aria-label="Service provider and overlay networking"><div className="builder-provider-title"><div><span>SERVICE PROVIDER / OVERLAY</span><strong>UNDERLAY TRUTH → ENCAPSULATION → OVERLAY</strong></div><small>{provider.tunnels.length} TUNNELS · {provider.mpls.lsps.length} LSPS · {provider.vxlan.vnis.length} VNIS</small></div><button className="builder-provider-open" onClick={()=>setOpen(true)}>OPEN PROVIDER MODEL</button><small className="builder-provider-boundary">ADVANCED PROVIDER PROJECTIONS STAY UNMOUNTED UNTIL OPENED · OSPF/BGP INSPECTION DOES NOT PAY THEIR DOM OR COMPUTE COST.</small></section>;
  return <><button className="builder-provider-close" onClick={()=>setOpen(false)}>CLOSE PROVIDER MODEL</button><BuilderProviderPanelContent {...props}/></>;
}
